### ISSUE TITLE
[BUG] Error while building

### ISSUE THREAD

**Issue by Panquesito7** [UniKonf/Vibey#10]
### Description of the bug

I was setting up the project on Gitpod. While running `npm run build`, it crashed and displayed the following error:

```bash
...Error: Please define the NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY environment variables inside .env.local
    at Object.9107 (/workspace/DevConf/.next/server/chunks/107.js:24:11)
    at __webpack_require__ (/workspace/DevConf/.next/server/webpack-runtime.js:25:42)
    at Object.5970 (/workspace/DevConf/.next/server/pages/index.js:43:81)
    at __webpack_require__ (/workspace/DevConf/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/workspace/DevConf/.next/server/pages/index.js:310:39)
    at /workspace/DevConf/.next/server/pages/index.js:311:78
    at Function.__webpack_require__.X (/workspace/DevConf/.next/server/webpack-runtime.js:108:21)
    at /workspace/DevConf/.next/server/pages/index.js:311:47
    at Object.<anonymous> (/workspace/DevConf/.next/server/pages/index.js:314:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)

> Build error occurred
Error: Failed to collect page data for /
    at /workspace/DevConf/node_modules/next/dist/build/utils.js:949:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'Error'
```

The file is ignored by `.gitignore`. It seems there are missing parameters in the `.env.local` file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chandraprakash-Darji** [comment]
You just need to add env vars.

**Comment by Panquesito7** [comment]
> You just need to add env vars.

Where is that being added specifically?

**Comment by Chandraprakash-Darji** [comment]
in the file `env.local` you can check `.env.example` what variables are required to add.

**Comment by Panquesito7** [comment]
Seems to be ignored by Git, plus, I think it should be compilable without any further changes, IMO.

**Comment by mkubdev** [comment]
We can't share the actual Supabase production env David. But we should update the README on how to create one..

**Comment by ctoffanin** [comment]
It's ok for the `.env.local` file to be ignored by git. 
It's part of the local environment when developing and shouldn't be committed. Otherwise, there will be a constant file update at every PR from different contributors, assuming they all use different keys :).
Also, they shouldn't indeed add their production keys on a `.env` file.

What is missing here is mentioning that you need a `.env.local` file and the explanation of how to create such a file starting from the `.env.example` in the readme/contributor page.
At least this is my opinion.

**Comment by mkubdev** [comment]
> What is missing here is mentioning that you need a `.env.local` file and the explanation of how to create such a file starting from the `.env.example` in the readme/contributor page. At least this is my opinion.

I agree with that! I'm asking myself if Supabase is a good solution for this project. Contributors will need to log in into the supabase website, create their own instance, etc.. Using a embedd docker DB could be simpler (and cooler as we will implement our own CRUD)

@Panquesito7 is a docker MongoDB running on gitpod?

**Comment by Panquesito7** [comment]
> is a docker MongoDB running on gitpod?

Not sure about that completely 🤔 but it seemed the issue was with the `.env.local` file.
I also agree with @ctoffanin's comment 👍 got kinda confused at the start.

**Comment by ctoffanin** [comment]
> is a docker MongoDB running on gitpod?

I think it's doable, Gitpod accepts Dockerfile and there is the official image of the community edition of MongoDB.
I might be wrong, of course. I never did it before. 😂

**Comment by mkubdev** [comment]
> I think it's doable, Gitpod accepts Dockerfile and there is the official image of the community edition of MongoDB. I might be wrong, of course. I never did it before. 😂

Hey, i saw yesterday that the awesome LinkFree have[ a gitpod conf /w mongo](https://github.com/EddieHubCommunity/LinkFree/blob/main/.gitpod.Dockerfile) so it's look doable! Never did it, but let's try it! 😁

**Comment by ctoffanin** [comment]
> Hey, i saw yesterday that the awesome LinkFree have[ a gitpod conf /w mongo](https://github.com/EddieHubCommunity/LinkFree/blob/main/.gitpod.Dockerfile) so it's look doable! Never did it, but let's try it! 😁

Yeah, that's going to help a lot!
