### ISSUE TITLE
Remove Footer section from contributor's dashbboard

### ISSUE THREAD

**Issue by money8203** [UniKonf/Vibey#104]
### Description of the bug

There's a footer section in the contributor's dashboard which is looking odd and isn't needed there, so it is better to remove the section from there.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SamantaTarun** [comment]
@money8203 should i remove the below footer section?
![image](https://user-images.githubusercontent.com/55488549/236764453-a087a2c5-f682-42c9-a977-05a7c9e9bebb.png)

**Comment by money8203** [comment]
@tarunsamanta2k20 I am talking about the footer section in the contributor's dashboard. You can see the image below. 

For that you need to first visit 'get started' on the top right side -> sign up -> then you can see the contributor's dashboard, from there you need to remove it.

![image](https://user-images.githubusercontent.com/89864818/236844929-18bedf31-1bb8-431a-b1ab-670e2bc1b9ca.png)
