### ISSUE TITLE
[FEATURE] Update Events 

### ISSUE THREAD

**Issue by himanshu1221** [UniKonf/Vibey#107]
### Detailed description

On the website, there are several events which are already done but still are shown in upcoming event 

![Screenshot from 2023-05-02 22-25-52](https://user-images.githubusercontent.com/32031706/235733407-447abdd8-faa9-4b04-a5b7-7e3dee41dad0.png)

### Context

It will enhance the use case of the website as outdated events will automatically be delisted or can be shown in past event section

### Possible implementation

we can ask the person to add `end date` of the event along with the start date of the event so we can tweak the website accordingly 

### Additional information

nope!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by money8203** [comment]
Thanks for raising the issue @himanshu1221, we are current working on the same. You'll get website updated by probably end of next week :)
