### ISSUE TITLE
[BUG] Authentication modal fixes

### ISSUE THREAD

**Issue by tamalCodes** [UniKonf/Vibey#109]
### Description of the bug

I was looking at the authentication modal, and I noticed multiple issues which I think can be worked upon to greatly change the User Experience.

- The background is still scrollable even if we are opening the authentication modal. This might not be a huge bug but is a bad user experience as I might not want to scroll through the background.

- Also wouldn't it be great if on the Signup page instead of `Signin with Google` it said `Signup with Google` ? 

- Suppose I have filled out the form, and then by mistake, I click outside the modal, the modal closes as well as the data is gone. I need to fill everything up again. What I'd suggest is to not make the modal go away when we are clicking outside.

- When we fill up the password incorrectly it says that `String must contain at least 8 character(s)` We can change the word `String` to `Password` as I think a user might not understand the meaning of `String`.

- There is no regex/checker for names, we are easily able to input numbers instead of words.

- After the registration is made, the background is changed first, and after that, the `alert` appears which has a significantly broken text `Successfully created account with ID:` .

- The modal is not closed after that, the data is also not cleared which might lead to confusion.

I think a lot can be improved, I am willing to work on it, we can also change the alert to something advanced like [React toastify](https://www.npmjs.com/package/react-toastify) which is much more good looking & clean. Also, the Message can be changed to `Account created successfully` and after that, the modal will close & only then the page will go to `/dashboard`.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/72851613/236490930-dd7ca3e3-8410-45dd-b635-78bd592ee397.png)

![image](https://user-images.githubusercontent.com/72851613/236493514-f5a2d120-5e86-44f6-b753-a88b29d65336.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Hii @IAmTamal Thanks for creating the issue. would you like to work on the issue?

**Comment by tamalCodes** [comment]
Sure, I'll do some fixes !

**Comment by tamalCodes** [comment]
@Deepu178 , i followed the exact steps to start the app, but I am encountering an error - and I am partly sure that this might be because of the missing `.env` values. 

Here's the code that gives me the error at `src\lib\db\useAppwriteClient.tsx `

```js
client
  .setEndpoint(process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT as string) // API Endpoint
  .setProject(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID as string);
```

**Screenshot for the same :** 

![image](https://user-images.githubusercontent.com/72851613/236634741-07d03820-8abe-44e0-83e1-8d7b5cbc3700.png)

**Comment by Deepu178** [comment]
@IAmTamal yess this is due to env file.
We are working on documentation so users can create their own credentials to run the project locally.

**Comment by money8203** [comment]
@IAmTamal you can pair up with @Deepu178 in our discord channel whenever you're free!

**Comment by tamalCodes** [comment]
> @IAmTamal you can pair up with @Deepu178 in our discord channel whenever you're free!

Sure, I was actually waiting for any updates on the `.env` bug.
BTW, can you drop in the Discord link here ?

**Comment by Deepu178** [comment]
@IAmTamal 
Discord link: https://discord.com/invite/Ryh2Mpxcnc
