### ISSUE TITLE
[BUG] Wrong CoC link

### ISSUE THREAD

**Issue by Panquesito7** [UniKonf/Vibey#11]
### Description of the bug

In the issue templates, at the bottom, there's a link to WebXDAO's Code of Conduct.
However, it seems to be pointing to an invalid repository.

https://github.com/WebXDAO/DevConf/blob/fd08226edfa36e7950ff9846c289c30a8e299904/.github/ISSUE_TEMPLATE/bug_report.yml#L27-L28

## Steps to contribute

_If you've already forked the repository, skip to step 3_

1. Fork the repository [**here**](https://github.com/WebXDAO/DevConf/fork).
2. Create a new branch named `fix_coc_link`.
3. Open the `.github/ISSUE_TEMPLATE/bug_report.yml`.
4. Replace line 28 contents with the following content:

```markdown
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/WebXDAO/start-here/blob/main/CODE_OF_CONDUCT.md)
```

5. Commit and push your changes.
6. Create a [**pull request**](https://github.com/WebXDAO/DevConf/compare).
7. You're done now! 🎉 You just have to wait until the maintainers review your PR.

If you need any help, don't hesitate to ask here or on our [**Discord server**](https://discord.gg/TSRwqx4K2v)! 🙂

### Add any other context about the problem here

This is a good first issue. Please leave it open to first-time contributors and beginners.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hey, well spotted. Thanks david !

**Comment by 0papi** [comment]
assign this to me
