### ISSUE TITLE
[BUG] ERROR WHILE INSTALLING

### ISSUE THREAD

**Issue by abhinav2712** [UniKonf/Vibey#110]
### Description of the bug

On installing after running `yarn run dev` I am facing this issue, someone do assist

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/68495520/236645111-5f7f1362-2e26-4863-83dd-ebe33d246ad2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sohankasturi** [comment]
Resolved that issue in the following Pull Request do go and check the PR https://github.com/UniKonf/vibey/pull/108/commits/3f79bc1407a408f12787f2442d0ea97ef64f3343

**Comment by money8203** [comment]
Did your issue get resolved @abhinav2712 ?

**Comment by abhinav2712** [comment]
> Did your issue get resolved @abhinav2712 ?

I will just check

**Comment by Deepu178** [comment]
Just added the documentation for creating the project on Appwrite and get projectId, and endPoint
