### ISSUE TITLE
[BUG] Not Correct Link

### ISSUE THREAD

**Issue by justankiit** [UniKonf/Vibey#111]
### Description of the bug

When we click on Join in the Events Section, We goes to only one Website whether it is API Day or Kubecon'23 ,if I click on join It goes to Same API Day Website.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/111564362/236692315-539aa312-a799-4782-b17a-4424e0a4d330.png)

### Add any other context about the problem here

We Can change the Wrong link by Right link in the href tag (link)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by money8203** [comment]
Thanks for raising the issue Ankit, we'll fix it soon!
