### ISSUE TITLE
create form for adding events, meetups, hackathons and CFPs for contibutors

### ISSUE THREAD

**Issue by tanishqamitra** [UniKonf/Vibey#115]
### Detailed description

Adding events to the database

### Context

Form for contributors to add events 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evoxf1** [comment]
want to contribute to your project.....

**Comment by evoxf1** [comment]
is there a file for this or can i create a new one

**Comment by ashishsurya** [comment]
can contribute if assigned under **GSSOC'23**

**Comment by Deepu178** [comment]
@evoxf1 you can work on existing issues or can create a new issue to work on. Let me know

**Comment by Deepu178** [comment]
@ashishsurya you can contribute to the project by working on existing issues or create new issue and get assigned
Start working on the issue

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Deepu178** [comment]
@ashishsurya This is the issue for creating a form on frontend side and all the events will be added through this form. So if you still would like to work on this issue. let me know

**Comment by ashishsurya** [comment]
Yeah, will work

**Comment by ashishsurya** [comment]
### At first can you answer some of my doubts
1. is form needed only for events (or) also for hackathons.
1. what are the details needed for an event to be added.
1. schema for event in db

**Comment by Deepu178** [comment]
1. The form is needed for Hackathons, Events and CFPs.
2. Name of the event, details of the event, date of the event, location, tags, links, theme, social profiles.
3. We are using appwrite for backend as a service and appwrite cloud for creating the database.

**Comment by Deepu178** [comment]
@ashishsurya  Should i assign the issue?

**Comment by ashishsurya** [comment]
> @ashishsurya  Should i assign the issue?

Yes, you can assign it to me I will start working on it

**Comment by Deepu178** [comment]
I have assigned the issue and looking forward for your pr soon. Good luck!

**Comment by ashishsurya** [comment]
@Deepu178 where does the form go, is that in `home page (or) dashboard page`

**Comment by Deepu178** [comment]
It goes to the Dashboard page @ashishsurya

**Comment by Deepu178** [comment]
@ashishsurya any update?

**Comment by Deepu178** [comment]
@ashishsurya I have to unassign the issue if I don't get any update from your side.

**Comment by vishnu9865** [comment]
@Deepu178 Sir, I would like to contribute to this project under GSSoC'23. I have noticed that we are currently moving from appwrite to nodejs. I have experience working with both of them. Therefore, I will implement this feature using Appwrite later on we can use the ExpressJS/NodeJS API backend instead. Is this ok with you.
If so, please do assign me this issue. 🚀🚀👍🏽😊
Thank you in advance.
regards,
@vishnu9865

**Comment by Deepu178** [comment]
@vishnu9865  I'm assigning this issue what you need to do is create a form on client side to add events, hackathons and cfps. 
Looking forward to review your pr!

**Comment by amanbairagi30** [comment]
Sir , I would like to contribute to this issue, please assign me this issue , I am experienced in Creating rest API and implementing the backend to it

**Comment by vishnu9865** [comment]
Guys, I'm almost finished with the Issue, just had college work in between, will be soon creating a PR.

**Comment by Deepu178** [comment]
@vishnu9865 Any update on the issue?

**Comment by vishnu9865** [comment]
Yeah, sorry for the inconvenience, couldn't work on it due to health complication on last 2 days, working on it right now as I type this. I apologise for the further delay. I want to make it up to you. is PR tomorrow morning at the earliest okay for you ?

**Comment by Deepu178** [comment]
@vishnu9865 no need to say sorry for that I just wanted an update. It's alright if it's delayed and health is the most important in any scenario.
You can take your time and whenever you feel healthy then you can create the pr. Take care 😌

**Comment by Isha988** [comment]
@Deepu178 I want to work on this

**Comment by Deepu178** [comment]
I have assigned the issue @Isha988  and you can start working on the issue.

**Comment by Deepu178** [comment]
@Isha988 Any update on this issue?

**Comment by satya-nishanth** [comment]
@Deepu178 
Is anyone still working on this?

**Comment by Deepu178** [comment]
@nish9142 Isha is working on this issue.
