### ISSUE TITLE
Update the README banner

### ISSUE THREAD

**Issue by money8203** [UniKonf/Vibey#118]
### Description of the bug

Update the text in the banner "Find your next developer conference and workshop"

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/89864818/de3839ee-ad12-43fe-b261-7b76d987f25f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ghat0tkach** [comment]
May i work on this issue?

**Comment by Deepu178** [comment]
@Ghat0tkach Yes you can work on this issue.

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach Yes you can work on this issue.

My i get the figma file of this banner?or the text-style background to customize it

**Comment by Deepu178** [comment]
@Chandraprakash-Darji can you share the Figma file?

**Comment by money8203** [comment]
@Ghat0tkach you can create a figma file for the banner and suggest it to us!

**Comment by Ghat0tkach** [comment]
@money8203 sure thank you , i do apologise for being inactive due to my end sem exams .
Will do it quickly after 7th.

Thank you

**Comment by Ghat0tkach** [comment]
I was also thinking of changing banner based on the basis of light/dark mode.
here is for the dark mode
![image](https://github.com/UniKonf/vibey/assets/59855919/84c5d641-dcf9-443a-8f08-eed311fd21fc)
for light mode
![image](https://github.com/UniKonf/vibey/assets/59855919/3faaed37-df9d-4907-aa0a-b609876fb4c1)
