### ISSUE TITLE
[BUG] Improve Navbar visibility in light mode: Change hamburger icon color and hover color for button

### ISSUE THREAD

**Issue by SirSimon162** [UniKonf/Vibey#123]
### Description of the bug

In light mode, the 'Get Started' text in the button in Navbar is not properly visible on hover and the hamburger icon in navbar in not visible on smaller screens. I have attached screenshots of the issue.

### Screenshots
![issue1](https://github.com/UniKonf/vibey/assets/103681122/e7f6d674-ef31-41b7-b4b3-267cc631b4fa)
![issue 2](https://github.com/UniKonf/vibey/assets/103681122/6686f532-a633-4345-8e16-62129f2a5638)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Hii @SirSimon162 Do you want to work on this issue?

**Comment by SirSimon162** [comment]
Sure! @Deepu178

**Comment by SirSimon162** [comment]
@Deepu178 Can you assign me this issue

**Comment by Deepu178** [comment]
@SirSimon162  assigned the  issue if you face any issue please feel free to ping me or any maintainer.
