### ISSUE TITLE
Improve the Footer Section

### ISSUE THREAD

**Issue by money8203** [UniKonf/Vibey#125]
### Detailed description

Add a footer section that could include links to important pages, such as the contact page, about page, and social media profiles. It could also provide legal information, such as terms and conditions and privacy policy.

### Context

Adding a footer section would greatly enhance the user experience and provide important information and links to users.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WIZN0DE** [comment]
Hi, I would like to improve the footer section.

**Comment by Anushka20365** [comment]
Hello @money8203 sir ,
I'm Anushka Anand . I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
Adobe Illustrator | Figma | Canva | HTML5, CSS3, JS, Bootstrap | Python, Django | Php, mysql | MERN | Responsive Design |

Can you please assign this issue to me.

**Comment by Deepu178** [comment]
@Anushka20365 You can start working on this issue.

**Comment by WIZN0DE** [comment]
Hi @Deepu178 I don't want to sound rude but I asked first for the issue to be assigned to me. I too am a GSSOC 23 contributer.

**Comment by Deepu178** [comment]
@slayeh17 missed your comment sorry for that.

**Comment by Deepu178** [comment]
@slayeh17 if you like then both of you can work on this issue in pair.

**Comment by WIZN0DE** [comment]
> @slayeh17 if you like then both of you can work on this issue in pair.

Won't there be a conflict ?. It's fine if @Anushka20365 just resolves this issue. I'll go look for another.

**Comment by money8203** [comment]
@Anushka20365 could you please state whether you've start working on the issue or not ? If yes then you can continue and @slayeh17 we will assign another issue to you based on your tech stacks and vice versa!

**Comment by WIZN0DE** [comment]
Hi @money8203 can I start working on this issue? Since @Anushka20365 doesn't seem to be responding.

**Comment by Deepu178** [comment]
@slayeh17 you can start work.
