### ISSUE TITLE
Improve the homepage of the website

### ISSUE THREAD

**Issue by money8203** [UniKonf/Vibey#129]
### Detailed description

I believe enhancing the homepage section would greatly enhance user experience and make a stronger first impression on visitors.

### Context

I would be happy to provide specific suggestions and collaborate with you to implement these improvements.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Isha988** [comment]
@money8203 I want to work on this issue and would be happy to make further discussion on this.

**Comment by Deepu178** [comment]
@Isha988 How are you gonna improve the homepage like how would you start implementing changes?

**Comment by Isha988** [comment]
@Deepu178 I am thinking of creating an improved design version of the homepage after the design gets approval from you people I will start working on it.

**Comment by Deepu178** [comment]
@Isha988 
You can start working on it.

**Comment by Deepu178** [comment]
@Isha988 
You can start working on it.

**Comment by money8203** [comment]
@Isha988 Have you joined our discord server?

**Comment by Isha988** [comment]
@money8203 I haven't, Would you please share the link?

**Comment by money8203** [comment]
> @money8203 I haven't, Would you please share the link?

Here you go https://discord.gg/MhHSnebw

**Comment by evoxf1** [comment]
i would like to contribute to the project...

**Comment by Deepu178** [comment]
@evoxf1 Thanks for showing interest to the project for making contribution. You can check out open issues or you can open new issues. Thanks

**Comment by Isha988** [comment]
@Deepu178  and @money8203 
Link of figma file: https://www.figma.com/file/hQQOVhqRGVfA6R9sFJGpLb/vibey?type=design&node-id=0%3A1&t=rIYU5iSEccDbDl6o-1

This is for the first time that I have created a web design and used figma so please be little lenient while checking and empty  circle present in design are for icons.
For small screens, single event card will be shown in each row and navbar will get collapsed. 
I hope you you get the idea of what changes I want to bring, your suggestions requested.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Deepu178** [comment]
@syedawanya18 Actually it is already assigned to @Isha988 so you can explore other issues.
