### ISSUE TITLE
[BUG] iOS overlapping menu issue

### ISSUE THREAD

**Issue by mkubdev** [UniKonf/Vibey#13]
### Description of the bug

On iOS devices, the overlapping menu is breaked.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/50140834/203504211-5fa3d5a1-cbdc-4d72-af0a-9c50e97cb7cf.png)

### Add any other context about the problem here

Sounds like an attribute compatibility issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by haris-75** [comment]
Hey @mkubdev assign this to me.

**Comment by mkubdev** [comment]
> Hey @mkubdev assign this to me.

Hi @haris-75! Happy new year, sorry for the late reply. I'm assigning you!
