### ISSUE TITLE
Add  CFP page to the website

### ISSUE THREAD

**Issue by money8203** [UniKonf/Vibey#133]
### Detailed description

Currently our website doesn't have a call for papers/speakers section, it should be created to list all the CFP's opening at any tech conferences/meetups.

**Comment by itshypon** [comment]
Do we have to collect data of CFP for all events or will it be provided?

**Comment by money8203** [comment]
It'll be provided but first of all you need to create  a design for the page and start working on it.

**Comment by Deepu178** [comment]
This issue has been completed with another pr so no need to work on that and I'm closing this issue for now.
