### ISSUE TITLE
Global Hack Week

### ISSUE THREAD

**Issue by Ayaan49** [UniKonf/Vibey#134]
### Event Name

MLH Global Hack Week 

### Short Description of the Event ( 20 words )

At Global Hack Week: Security, spend the week by learning, building, and hacking all things security related.

### Event Date and Time

05/06/23 - 12/06/23

### Event Page Link

https://ghw.mlh.io/events/security-week

### Themes

SECURITY

### Facebook

https://www.facebook.com/MajorLeagueHacking

### Github

https://github.com/MLH

### Instagram

https://www.instagram.com/mlhacks/

### LinkedIn

https://www.linkedin.com/company/major-league-hacking

### Twitter

https://twitter.com/mlhacks

### Discord

https://twitter.com/mlhacks

**Comment by Deepu178** [comment]
@Ayaan49 Would you like to work on this issue?

**Comment by Ayaan49** [comment]
> @Ayaan49 Would you like to work on this issue?

Yes
