### ISSUE TITLE
New Issue Encountered - Hydration Error and Key Duplication

### ISSUE THREAD

**Issue by shyamenk** [UniKonf/Vibey#137]
### Description of the bug

**While running the server** `npm run dev`

I am currently working on the project and have encountered a couple of issues while running the server using the command `npm run dev `. I will provide an update once I fix the problem. The details of the issues are as follows:

- Error: Text content does not match server-rendered HTML - Hydration Error:
When running the server, I am receiving an error indicating that the text content does not match the server-rendered HTML. This error is causing issues with the hydration process.

- Warning: Encountered two children with the same key, 1 - Key Duplication Error:
Additionally, there is a warning indicating that there are two children with the same key value of 1. As per best practices, keys should be unique to ensure proper rendering and component identification.

I am actively investigating these issues and will provide an update as soon as I have resolved them. If anyone has encountered similar problems or has any insights on how to address these errors, please feel free to share your thoughts.

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/4456770/6143c388-184f-458a-99c6-a83861f604b8)

![image](https://github.com/UniKonf/vibey/assets/4456770/72b89355-cf2f-4d7e-b28b-0b8263d49a22)

![image](https://github.com/UniKonf/vibey/assets/4456770/31c364fe-e146-442d-b75c-6174031e0a89)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Thanks for taking out time to explain the issue. If you want to work on this issue @shyamenk 
Let me know
