### ISSUE TITLE
Dark mode to light mode transition causes text visibility problem in events section

### ISSUE THREAD

**Issue by Saqlain-qark** [UniKonf/Vibey#138]
When I switch the events page in vibey from dark mode to light mode, the text in the events section changes from white to black, which is good. However, the background image in the events section remains dark, making the text hard to see. I have attached an image to show the problem. ![Screenshot_20230519-230816_Chrome.png](https://github.com/UniKonf/vibey/assets/61051533/fa66f369-ce19-484a-87f5-89923638ecde)

**Comment by Harshavardhana-B-S** [comment]
Girl_Script_Summer_Of_Code_23
I will resolve this issue. I am working on the best color combination.
I have shared the sample images.
can u assign me this issue?

![image](https://github.com/UniKonf/vibey/assets/97674335/be7c34cf-1ae8-4581-8d88-33f9531a85da)

**Comment by Deepu178** [comment]
@Saqlain-qark Do you work on this issue?

**Comment by Saqlain-qark** [comment]
No let him do if he wants
