### ISSUE TITLE
[Core] Remove Supabase - Add MongoDB - Use JSON data?

### ISSUE THREAD

**Issue by mkubdev** [UniKonf/Vibey#14]
### Description of the bug

Remove the Supabase integration, and replace it by a Mongo docker database.

### Add any other context about the problem here

We think supabase will slow down contributions (#10), and it's cooler if we have our own database:
* Add our own CRUD
* Add our own Authentication layer
* Add our own back-office
* ....

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ctoffanin** [comment]
How's it going with this @mkubdev?

**Comment by mkubdev** [comment]
> How's it going with this @mkubdev?

Hi @ctoffanin! With the arrival of the holidays and the end-of-year projects to be delivered, it's hard to find the time to implement this yet properly. It's hosted on a local branch that'll push in the evening.

**Comment by ctoffanin** [comment]
Of course @mkubdev no pressure. I was just curious to know how it was going 😀

**Comment by mkubdev** [comment]
> Of course @mkubdev no pressure. I was just curious to know how it was going 😀

Sure thanks a lot @ctoffanin 🙏

The branch currently contain:
* Dockerfile for mongo
* Mongoose middleware
* An `getAllEvents()` at `/api/events/getall` wich return all the events.

**Comment by mkubdev** [comment]
Hey there! Is this still on the roadmap?
