### ISSUE TITLE
[BUG]  When a user is logged in and if he is on light mode the color visibility  of texts are not good

### ISSUE THREAD

**Issue by Mudassirkhan2** [UniKonf/Vibey#142]
### Description of the bug

When a user is logged in and if he is on light mode the color visibility  of texts are not good

### Please add screenshots (if applicable)

![Screenshot 2023-05-20 100614](https://github.com/UniKonf/vibey/assets/106579572/531bb72e-80c2-4a72-8ee1-1b5ba0f66d4b)

### Add any other context about the problem here

i want to change the color to black When the user is in light mode.
I want to work on this issur under GSSOC 2023

FeedBack When a user is logged in its still showing the Button Get Started. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Mudassirkhan2 do you want to work on this issue?

**Comment by Mudassirkhan2** [comment]
> @Mudassirkhan2 do you want to work on this issue?

Yes will try my best.

**Comment by Mudassirkhan2** [comment]
label of gssoc @Deepu178

**Comment by Mudassirkhan2** [comment]
@Deepu178  i havent got points for this issue

**Comment by Deepu178** [comment]
@Mudassirkhan2  labels were not added to that pr and I added the appropriate labels and you will get your points for the pr soon. it may take 1 or 2 week to  update the leaderboard.
