### ISSUE TITLE
[BUG] Light mode is not loading properly

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#143]
### Description of the bug

If you set the mode to light and refresh the page for some fraction of a second dark mode is loaded then convert it to light mode.
But no error for the dark mode.

I would like to work on it for gssoc23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38 Do you want to work on this issue?

**Comment by suzy-g38** [comment]
> @suzy-g38 Do you want to work on this issue?

Yes
