### ISSUE TITLE
[BUG] All Events page is showing 404

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#144]
### Description of the bug

When we click on the all events button, it gets directed to the upcoming events page which is showing 404.

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/62666287/cb1f6be4-fc5a-4ecf-9877-f65c74007359)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suzy-g38** [comment]
> ### Description of the bug
> When we click on the all events button, it gets directed to the upcoming events page which is showing 404.
> 
> ### Please add screenshots (if applicable)
> ![image](https://user-images.githubusercontent.com/62666287/239679054-cb1f6be4-fc5a-4ecf-9877-f65c74007359.png)
> 
> ### Add any other context about the problem here
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

I would like to work on it for gssoc23

**Comment by Deepu178** [comment]
@suzy-g38 do you want to work on this issue?

**Comment by suzy-g38** [comment]
> @suzy-g38 do you want to work on this issue?

Yes

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by money8203** [comment]
The issue has been resolved under a part of previous issue, thanks for raising though! You can checkout other issues and start working on them!
