### ISSUE TITLE
[FEATURE] Search events based on cities

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#145]
### Detailed description

Create some tags for cities and if the user clicks on a city it will show the list of upcoming events going to happen in that city.

### Context

As events can be based on multiple cities, so creating some tags for the cities and showing all the events going to happen in that city will give users a much better experience.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashishsurya** [comment]
assign this to me, can contribute to this under **GSSOC'23**

**Comment by suzy-g38** [comment]
> ### Detailed description
> Create some tags for cities and if the user clicks on a city it will show the list of upcoming events going to happen in that city.
> 
> ### Context
> As events can be based on multiple cities, so creating some tags for the cities and showing all the events going to happen in that city will give users a much better experience.
> 
> I would like to work on it for gssoc23
> 
> ### Possible implementation
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

 ### Hey, I have created this issue and already mentioned that I want to work on it

**Comment by Deepu178** [comment]
@suzy-g38 do you want to work on this issue?

**Comment by suzy-g38** [comment]
> @suzy-g38 do you want to work on this issue?

yes

**Comment by ayesha-firdaus** [comment]
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by Deepu178** [comment]
@suzy-g38 you can start working on this issue

**Comment by money8203** [comment]
Hey @suzy-g38 ping me or @Deepu178 and let's have a discussion around the issue and your ideas
