### ISSUE TITLE
form fields overflowing the container 

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#146]
### Description of the bug

**Form fields of sign in and log in form are overflowing the container for mobile screen .** Please assign this to me, I can fix this issue.

### Please add screenshots (if applicable)

![Screenshot_2023-05-20-18-02-27-02_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/UniKonf/vibey/assets/59419650/74172e45-c1e5-460a-b0f1-be30a7f0cf03)
![Screenshot_2023-05-20-18-02-21-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/UniKonf/vibey/assets/59419650/e1d073fa-aa9b-4607-ad74-f3fa2d53b37b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab you can start working on this issue.

**Comment by Varghab** [comment]
@Deepu178 made the required changes and created a pull request, please check.

**Comment by Deepu178** [comment]
Can you add screenshot?

**Comment by Varghab** [comment]
@Deepu178 I have updated my PR with screenshots, please check.

**Comment by Varghab** [comment]
@Deepu178  Hey, my PR already got merged, can you mark it under GSSoC '23
