### ISSUE TITLE
[BUG] event cards overflowing container in the events route 

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#147]
### Description of the bug

All the event cards are overflowing the container. Please assign this to me I can definitely fix this. 

### Please add screenshots (if applicable)

![IMG_20230520_181503](https://github.com/UniKonf/vibey/assets/59419650/f4bc51a3-5beb-4bee-ae97-7405446a47f3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab Do you want to work on this issue?

**Comment by Deepu178** [comment]
@Varghab I have assigned the issue you can start working on this issue. If you find any difficulty in running locally let me know

**Comment by Varghab** [comment]
@Deepu178 made the required changes and created a pull request, please check.

**Comment by Varghab** [comment]
Deepu178  Hey, my PR already got merged, can you mark it under GSSoC '23

**Comment by Deepu178** [comment]
@Varghab can you please share the pr number?

**Comment by Varghab** [comment]
@Deepu178 My PRs are #151 #161 #146, including this. Also, would you review these issues - #267 #268 and #269? And for the issue #267 you indicated to create a new PR but didn't assign me, would you please assign me?

**Comment by Deepu178** [comment]
@Varghab Are  you contributing under GSSoC.
I have assigned #267 as you create pr for this then I'll assign other issues also.
Thanks for reminding me about those issues.

**Comment by Varghab** [comment]
@Deepu178 Thanks for assigning and yes I am contributing under GSSoC.
