### ISSUE TITLE
[FEATURE] Creating a better 404 page

### ISSUE THREAD

**Issue by An525ish** [UniKonf/Vibey#148]
### Detailed description

I want to enhance the look of the 404 page

### Context

A 404 page can help keep the traffic on your website and assist users in finding what they’re looking for and it generally brings a good impact to the user when they found it well designed and structured

### Possible implementation

- reason for the error
- some animated styles to enhance the overall look
- back to homepage button

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@An525ish I have assigned the issue and now you can start working on the issue.

**Comment by Deepu178** [comment]
Have you joined the discord server for the updates?

**Comment by An525ish** [comment]
> @An525ish I have assigned the issue and now you can start working on the issue.

yeah, I have joined..

**Comment by Deepu178** [comment]
@An525ish is there any update about the issue?

**Comment by Deepu178** [comment]
@An525ish I'm not able to see any progress on this issue so I'm closing this issue as of now
