### ISSUE TITLE
[BUG] Login or Signup Section unresponsiveness on Smaller Devices

### ISSUE THREAD

**Issue by manaver** [UniKonf/Vibey#149]
### Title
Login or Signup Section unresponsiveness on Smaller Devices

### Description
I would like to report an issue with the login page where the login or signup section is fixed on smaller devices, such as mobile phones or tablets. This causes the section to remain static and not adapt to the screen size, resulting in buttons or form fields being hidden or inaccessible depending on the device's height.

### Expected Behavior
1. The login or signup section should be responsive and adjust to smaller device screens i.e. scrollable on small devices.
2. Buttons, form fields, and other elements within the section should be displayed properly on all devices, regardless of the screen height.

### Additional Information
- I am interested in working on this issue and making the necessary changes to improve the responsiveness of the login or signup section.
- Please provide guidance or suggestions on how to implement a responsive design solution for the login or signup section on smaller devices.
- It is recommended to use media queries or other suitable techniques to achieve the desired responsive behavior for the section.

**I am interested in working on this issue and I am committed to resolving it efficiently and effectively.**

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/78682260/bff11ebe-2b60-4357-a894-c7b84f04f0a5)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@manaver do you want to work on this issue?

**Comment by manaver** [comment]
> @manaver do you want to work on this issue?

Yes. I'm a gssoc contributor and I would be happy to work on this issue😀

**Comment by manaver** [comment]
@Deepu178 please asign this issue to me😄

**Comment by manaver** [comment]
@Deepu178  is gssoc tag is needed on the issue?

**Comment by manaver** [comment]
if yes then please add one😄
