### ISSUE TITLE
[FEATURE] Remove the bottom border-radius of the main container

### ISSUE THREAD

**Issue by mkubdev** [UniKonf/Vibey#15]
### Detailed description

* We should remove the border-radius of the bottom of the main container:
![image](https://user-images.githubusercontent.com/50140834/203579896-fa2e0f4a-8ca8-448f-a9b5-62e76357a7a0.png)

### Context

It's not mandatory, but looks better imo.

### Possible implementation

Replace `rounded-3xl` from https://github.com/WebXDAO/DevConf/blob/aa6cc420c165a542e19badf928833f5247ea75ab/src/pages/index.tsx#L15

By `rounded-t-3xl` from [Tailwind ](https://tailwindcss.com/docs/border-radius)documentation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hariscs** [comment]
@mkubdev  assign me this
