### ISSUE TITLE
I want to make dark -mode switching option to top right- corner  

### ISSUE THREAD

**Issue by bhaskarkumar1** [UniKonf/Vibey#150]
### Detailed description

i want to make dark -mode switching option to top right- corner  

### Context

It will easily allow users to look for changing theme. As no want to search for features and we want to easily accessible and we dont want to waste our feature.

### Possible implementation

just moving the mode container to top right and fix it there 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Thanks for suggesting but actually we are no looking for that change right so I'm closing this issue.
