### ISSUE TITLE
[FEATURE] Better menu bar with icons

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#152]
### Detailed description

The Menubar looks too simple, I can make it more interactive by adding icons and other hover effects. **Also, for the mobile and tablet view, placing the Get Started button and GitHub icon/social handles of Vibey in the Menubar would make the navbar clean and elegant.** 

### Context

Icons grab users' attention faster than simple text. Adding icons for each menu item in the Menubar would instantly give an idea to users about menu items. Also transferring the Get Started button to the Menubar would give liberty to users to view it or not and also it looks clean and elegant. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab you can work on this issue.

**Comment by Varghab** [comment]
@Deepu178 I have created the PR, please check.
