### ISSUE TITLE
[BUG] Light mode Bug

### ISSUE THREAD

**Issue by himanshu1221** [UniKonf/Vibey#156]
### Description of the bug

when we switch to light mode in dashboard text remains the same 
i want to work on this under GSSoC23

### Please add screenshots (if applicable)

![Screenshot from 2023-05-21 14-17-26](https://github.com/UniKonf/vibey/assets/32031706/bb011430-45b2-46f7-b83b-99a9877b8e49)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Varghab** [comment]
@himanshu1221  Someone was already assigned for this issue, check #158.

**Comment by himanshu1221** [comment]
Oh okay !
