### ISSUE TITLE
[BUG] Replace steps to add an event

### ISSUE THREAD

**Issue by mkubdev** [UniKonf/Vibey#16]
### Description of the bug

Steps are wrong, need to replace by something like:

1. Open a new issue
2. Add event detail in the issue
3. Submit issue

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/50140834/203584011-4acd36f1-8900-45de-9550-51512ac72aa7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hariscs** [comment]
i would like to work on this issue

**Comment by mkubdev** [comment]
Ok i assign you @hariscs :D
