### ISSUE TITLE
[BUG] Signup and login form not changing theme

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#162]
### Description of the bug

Login form and signup form is not changing their theme when darkmode button is clicked. Please assign me under GSSoC'23 label. 

### Please add screenshots (if applicable)

![Screenshot_2023-05-21-18-02-25-44_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/UniKonf/vibey/assets/59419650/f2f93f64-6fde-4e9a-bafb-302bd0d5857f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Varghab** [comment]
@Deepu178 Hey, please review this issue.
