### ISSUE TITLE
[FEATURE] Form to add an event 

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#164]
### Detailed description

Hey, a form on the home page to list an event would be helpful. I can create an interactive form, **please assign me the task under GSSoC if not anyone working on it yet.** 

### Context

This change will make this website more diverse in terms of upcoming events. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by B2prakash** [comment]
assign this form to add an event to me . i can add so many event

**Comment by Chavisn** [comment]
I would to work on this issue. Please assign this to me.
