### ISSUE TITLE
[FEATURE] Dedicated page for each events

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#166]
### Detailed description

A dedicated page for each event where users can - 
- Get the brief of the event
- Know the timing of the event
- Know the venue of the event
- A button that will redirect the user to that event's homepage
- Social handles of the event

**Please assign me this feature update under GSSoC if not anyone already working on it.** 

### Context

This change is important because - 
- User will get an idea of the upcoming event while staying on the same website.
- I as a user would prefer this because this is much more convenient than visiting a new website and getting myself familiar with a new UI.
- Also, we are giving a user liberty to visit the event page rather than simply redirecting them to the page. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab That's really good idea and I'm really excited to hear from your side in details that how are you gonna implement that so I can assign this issue if you want to work on it.

**Comment by J-Harsh** [comment]
Hey @Varghab any update on this, or should we close this issue?

**Comment by Varghab** [comment]
@J-Harsh @Deepu178 Routes can be created by the name of the event - https://www.vibey.live/[Name_of_the_event]. 

- In the events.ts file under the constant folder, object keys like id, description, title, start time, etc are already created, we can add some more keys like - about, venue, speakers, and so on. 
- After that, we can simplify the event card on the homepage by only showing the name of the event, overview, and "know more" button. 
- And the "know more" button would redirect to the https://www.vibey.live/[Name_of_the_event] route, where all the details of the event will be given. After that, if anyone wants to visit the event's official site then we can add a button to send users to the official site. 

**Note - I am taking events as an example, this can also be done for hackathons and cfps. We have to create a few files like event.ts for hackathons and cfps also.**

I would be more than happy to work on it if I get assigned.

**Comment by Deepu178** [comment]
Ok @Varghab Thanks for clarifying the issue! I got your points. Are you gonna implement changes to the cfps and hackathons pages as well?

**Comment by Varghab** [comment]
@Deepu178 Yes, I would love to do this.

**Comment by Deepu178** [comment]
Ok @Varghab I'm assigning this issue to you and looking forward to review your pr.🚀

**Comment by Deepu178** [comment]
Any update on this issue @Varghab ?

**Comment by Varghab** [comment]
@Deepu178 Yes, I am working on it, I will try to complete it as soon as possible.
