### ISSUE TITLE
[FEATURE] Add a scroll to top navigation button 

### ISSUE THREAD

**Issue by abhinav-m22** [UniKonf/Vibey#168]
### Detailed description

There is an absence of a scroll-to-top button on the website. The website's user experience would be improved by the addition of this floating button.
Due to my prior experience in building for personal projects, I'd like to contribute this feature.

Please assign me the task under GSSoC'23.

### Context

The scroll-to-top nav button is a useful component of the web page as it routes the page back to the top on the main page.
As the length of the page increases, it becomes a tedious task to scroll back to top through mouse.

### Additional information

I want to work on this feature.
Please assign me the task under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sandeep0306** [comment]
Hii, i want to add scroll to top button which will be better for  user to navigate to top of page .please Assign me this issue under Gssoc'23

**Comment by J-Harsh** [comment]
Hey @abhinav-m22 , I have assigned the issue. You can start working on it now. Have fun

**Comment by abhinav-m22** [comment]
Hey @J-Harsh 
I have created a PR - #198 
Please have a look!

**Comment by rushabhpanbude** [comment]
@abhinav-m22 are you still working on this ?

**Comment by vk20july** [comment]
@J-Harsh sir i want to work on this issue under gssoc'23
