### ISSUE TITLE
[FEATURE] Add event date and time to card 

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [UniKonf/Vibey#17]
### Detailed description

Add the event date and time above the themes.
![image](https://user-images.githubusercontent.com/93640141/203588105-19d0e080-bfe2-4b68-b08b-4e0245bebfbc.png)

### Context

You can use `startTime` to add date.

The event component is located at `/src/components/Event`

### Possible implementation

Element you can add
```html
  <div className="mt-2 flex items-center justify-between">
            {new Date(startTime).toUTCString()}
    </div>
```
After:
![image](https://user-images.githubusercontent.com/93640141/203589665-5f22f072-a8db-4955-816f-0958813cc4db.png)

Update the type defination of Event 
```ts

export interface EventInterface {
  id: number;
  title: string;
  description: string;
  startTime: string;
  link: string;
  socials: Array<{ name: SocialIconsNameType; link: string }>;
  themes: string[];
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0papi** [comment]
assign this to me

**Comment by Chandraprakash-Darji** [comment]
Welcome, @0papi ... I assign you
