### ISSUE TITLE
[FEATURE] password visibility toggle in signup

### ISSUE THREAD

**Issue by SINJINI-G** [UniKonf/Vibey#170]
### Detailed description

Toggle the visibility of the password in user signup page on button click.

# After change
![image](https://github.com/UniKonf/vibey/assets/98143022/423bf5e6-4262-44a0-ba63-4d9a2b264d2e)

### Context

This will allow them to see if they have entered the password correctly or not which will improve the UX.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SINJINI-G** [comment]
Can you assign me this issue for gssoc?

**Comment by J-Harsh** [comment]
Sure @SINJINI-G , I am assigning you this issue under GSSOC'23. Good luck and have fun contributing. Adhere to the contribution.md guidelines

**Comment by vk20july** [comment]
@Deepu178 and @J-Harsh sir i want to work on this issue under gssoc'23
