### ISSUE TITLE
[BUG] Terms of Service and Privacy Policy links not working in SIGN UP

### ISSUE THREAD

**Issue by Ayan-M-Dev** [UniKonf/Vibey#171]
### Description of the bug

Terms of Service and Privacy Policy links not redirecting/working in the SIGN UP window

### Please add screenshots (if applicable)

![Screenshot 2023-05-22 065654](https://github.com/UniKonf/vibey/assets/101629997/3c59f5bd-21ae-4f81-a50c-f1be13f7b516)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ayan-M-Dev** [comment]
Please assign me the issue as I would do the required changes for it to work. [Contributor - GSSoC'23]

**Comment by evoxf1** [comment]
can i do this ?

**Comment by J-Harsh** [comment]
hey @Ayan-M-Dev what do you plan to add in the terms and services/privacy policy section?

**Comment by Ayan-M-Dev** [comment]
Hey @J-Harsh Well for there are is a list of things that would be there for both of the section.
For 'Terms and Services' 
- Acceptance of Terms: Users should explicitly agree to the terms and conditions before using the website or accessing any services.
- Description of Service: Clearly explain the purpose of Vibey as a web app to find online conferences and events for developers.
There are 6 more but out that these two would be at the top
For 'Privacy Policy'
- Information Collection: Detail the types of personal information collected from users, such as names, email addresses, and any additional information necessary for the functioning of the web app.
- Use of Information: Explain how the collected information will be used, such as for user authentication, communication, improvement of services, or aggregated analytics. If applicable, mention any targeted advertising or user profiling practices.
There are 6 more for this also but out that these two would be at the top

**Comment by Deepu178** [comment]
@Ayan-M-Dev do you want to still work on this issue?

**Comment by Ayan-M-Dev** [comment]
@Deepu178 Was waiting to get assigned so that i could work on the issue.

**Comment by Deepu178** [comment]
Are you contributing under GSSoC?

**Comment by Ayan-M-Dev** [comment]
Yes

**Comment by Deepu178** [comment]
I have assigned the issue you can start working on this. Good luck
