### ISSUE TITLE
[BUG] HackCBS and Hackerstellar card on the Event page is getting redirected to the same page.

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [UniKonf/Vibey#172]
### Description of the bug

HackCBS  and hackerstellar card on the Event page is getting redirected to the same page instead of their concerned websites.
<img width="939" alt="image" src="https://github.com/UniKonf/vibey/assets/70560812/fdee9840-0a02-4715-8408-81cac95f9aef">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GVishnudhasan** [comment]
Can I work upon this bug?

**Comment by money8203** [comment]
@Ishita-Ghosh-25 a pr already existed for the same. Events page will be updated soon.
