### ISSUE TITLE
[FEATURE] dynamic auto update year in footer

### ISSUE THREAD

**Issue by rushabhpanbude** [UniKonf/Vibey#174]
### Detailed description

current year in footer section will get auto update as per current year...developer does not need to change year manually 

### Context

developer does not need to change year manually

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
@rushabhpanbude are you from GSSOC'23?

**Comment by rushabhpanbude** [comment]
Yes

**Comment by J-Harsh** [comment]
Please mention the same when raising issues, it will help us track your contributions easily. 
I am assigning you this issue under GSSoC'23. Have fun while contributing.
Adhere to the contribution.md guidelines.

**Comment by rushabhpanbude** [comment]
Auto update year is already there 😅
You can close this issue

**Comment by J-Harsh** [comment]
My bad for not looking into it earlier, don't be awkward.
Try to find some another issue to work on @rushabhpanbude have fun <3
