### ISSUE TITLE
Enhance Upcoming Events Card with Gradient Colors. {GSSoC '23}

### ISSUE THREAD

**Issue by GVishnudhasan** [UniKonf/Vibey#177]
### Detailed description

I wish to enhance the card of the upcoming event by incorporating gradient colors into the theme. This addition will bring visual appeal and vibrancy to the card, making it more engaging for users.

### Context

The change is essential as it adds an aesthetic touch to the card of the upcoming event, making it visually appealing and captivating for users. By incorporating gradient colors, we can create a more immersive experience, capturing the attention of users and increasing their interest in upcoming events.

This change is important to me as it improves the overall user experience and aligns with modern design trends. As a user, I would enjoy seeing visually attractive upcoming event cards that utilize gradient colors.

### Possible implementation

1. Identify an appropriate color palette for the gradient that complements the existing theme.
2. Apply the gradient colors to the background or specific elements of the card of the upcoming event.
3. Ensure the gradient colors maintain the readability and accessibility of the card's content.
4. Test the implementation across different devices and screen sizes to ensure a consistent visual experience.

### Additional information

I will be happy to work on this enhancement. Please assign it to me under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
we have already changed card with update in new theme of the website so I'm closing this issue. Thanks for opening the issue and you can create more issues.
