### ISSUE TITLE
[BUG] Banner of website not displayed in README

### ISSUE THREAD

**Issue by mkswagger** [UniKonf/Vibey#178]
### Description of the bug

Title: Edit README to Address Banner Loading Issue

Description:
This issue focuses on resolving the problem of the banner not loading correctly in the README file of the repository. The current banner image is not displaying as intended, and we need to investigate and fix the loading issue.

### Please add screenshots (if applicable)

![Screenshot (1764)](https://github.com/UniKonf/vibey/assets/34826479/0b7003ce-5358-409f-bffe-0ac5f7f34bc1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkswagger** [comment]
Hi , I am a contributor in GSSOC'23, Please assign this issue to me

**Comment by J-Harsh** [comment]
You plan to add a banner on the readme file? because I am unable to replicate the bug

**Comment by mkswagger** [comment]
> You plan to add a banner on the readme file? because I am unable to replicate the bug

I noticed that there was a banner of the website in the README but it was glitchy like it wasnt showing at all, so maybe I can add the website's banner to the README properly?

**Comment by J-Harsh** [comment]
Hey @mkswagger I think we already have an open issue regarding the banner inside the readme file, feel free to find some another enhancement. I will be closing the issue for now
