### ISSUE TITLE
[BUG] Remove kubeHuddle 2023

### ISSUE THREAD

**Issue by afeefuddin** [UniKonf/Vibey#179]
### Description of the bug

We should remove KubeHuddle 2023 from the upcoming events as it is already over

### Please add screenshots (if applicable)

![Screenshot (21)](https://github.com/UniKonf/vibey/assets/126336384/1c933c15-f2bd-41a2-80c1-1e90338a4a8f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afeefuddin** [comment]
Please assign me this issue as I want to work on it!

**Comment by money8203** [comment]
Hey the event has already been removed!
