### ISSUE TITLE
[BUG] If there is too many social media event name wraps

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [UniKonf/Vibey#18]
### Description of the bug

![image](https://user-images.githubusercontent.com/93640141/203591221-5e0a2cef-ecae-4d58-86dd-112a47ffa424.png)

The name of the event is wrapping when there are more than 2-3 social handles. 

A potential Fix can be add `flex-wrap` to the parent container of it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hariscs** [comment]
assign me this

**Comment by Chandraprakash-Darji** [comment]
@hariscs I have assigned you. We will love to have your contribution
