### ISSUE TITLE
Hover effects on social media handles on upcoming events card[FEATURE]

### ISSUE THREAD

**Issue by AK4266** [UniKonf/Vibey#181]
### Detailed description

There is no hover effects on social media handles on upcoming events card

### Context

I think having hover effects on social media handles every where on the page and not having on upcoming events cards feels out of place. So, I think i will look better with hover effects. 

### Possible implementation

To implement same hover effect as other social media handles on the page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Sure go ahead an make the suggested UI changes.
Make sure the UI changes are in line with the existing design pattern of the website, so as to avoid causing inconsistency.
I am assigning you this issue under GSSOC'23 good luck and have fun

**Comment by Deepu178** [comment]
@AK4266 any further update on this issue?

**Comment by AK4266** [comment]
@Deepu178 Looks like someone has already resolved this issue. So, iam not working on this issue right now
