### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by shwetazade27** [UniKonf/Vibey#182]
### Detailed description

Adding about us , contact us  int navbar (Gssoc'23)

### Context

About us section is essential in any site as it gives overall idea about the website. Contact us section is also essential to get in contact with you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Hey @shwetazade27 you plan to make changes in the navbar or do you want to make new pages as well? Also please write better headlines when raising issues in future, it will help me and other maintainers to be more vigilant about the nature of issue

**Comment by shwetazade27** [comment]
@J-Harsh  I wanted to make changes in navbar and sorry for confusion.

**Comment by J-Harsh** [comment]
@shwetazade27 I think about us and contact us links are already present in the footer section of the website. There is already an issue regarding the re-designing of the footer page. Feel free to raise another issue and dont let this discourage you from contributions in the future
