### ISSUE TITLE
[BUG] <bug description> Signup page not completely showing and it is not scrolling down

### ISSUE THREAD

**Issue by Lakshyyaa** [UniKonf/Vibey#184]
### Description of the bug

the signup screen is not being fully shown as it pushed down by the navbar
please assign this to me under GSSOC i would like to fix this

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/99789174/685b094d-5b06-4d2c-a2df-bc4177684bab)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Alright @Lakshyyaa I am assigning you this issue under the GSSOC'23. Good luck and have fun contributing.

**Comment by Laxmankohar** [comment]
Hey @J-Harsh . I would like to work on this issue under Gssoc. Can you assign it to me?

**Comment by Deepu178** [comment]
@J-Harsh This issue has already been resolved so I'm closing this now.
