### ISSUE TITLE
[BUG] <bug description> signup(get started) showing even after login instead of logout

### ISSUE THREAD

**Issue by Lakshyyaa** [UniKonf/Vibey#185]
### Description of the bug

after logging in, it still shows get started button instead of logout
please assign this to me under GSSOC id like to fix this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
The get started button being there also allows the user to sign in even though they are already signed in. 
Would you like to solve that issue as well apart from just making UI changes?
