### ISSUE TITLE
Join button in Upcoming Events section is dislocated [FEATURE]

### ISSUE THREAD

**Issue by HimanshuNarware** [UniKonf/Vibey#187]
### Detailed description

The join button in the Upcoming Events section is dislocated, I want to resolve this issue, kindly assign me this issue.

### Context

I want to resolve the issue by align the button on right place , It improve the UI of website

### Additional information

![4](https://github.com/UniKonf/vibey/assets/83147410/825a06bd-b6d6-4113-910e-82eea89f46c3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Where do you plan to fit the content placed in the top right section?

**Comment by HimanshuNarware** [comment]
> Where do you plan to fit the content placed in the top right section?

I just want to align  second join btn with the first btn ,it just need litbit margin

**Comment by J-Harsh** [comment]
Alright, I have talked with our UI designer and if you want to make a ui change for the button make it something like this
![image](https://github.com/UniKonf/vibey/assets/56508036/183f0347-7509-41e4-9d58-f98a4f8f65aa)
at the bottom of the card

**Comment by J-Harsh** [comment]
hey @HimanshuNarware do you still want to work on this issue ?

**Comment by HimanshuNarware** [comment]
@J-Harsh every time i try to install yarn it stuck 

![145](https://github.com/UniKonf/vibey/assets/83147410/e52f5cbb-eccf-40fa-8c51-55a2484f943c)

**Comment by J-Harsh** [comment]
look up the documentation of yarn, and try installing it

**Comment by HimanshuNarware** [comment]
> look up the documentation of yarn, and try installing it

ok
