### ISSUE TITLE
[FEATURE] Add Husky

### ISSUE THREAD

**Issue by ctoffanin** [UniKonf/Vibey#19]
### Detailed description

With Husky, we can run a pre-commit file running ESLint and Prettier to check for errors and correctly format the files before a commit is completed. 
I also would like to suggest improving the Prettier file.

### Context

It avoids commits/PRs containing errors and weird code formatting.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ctoffanin** [comment]
If you have nobody who can work on this, you can assign it to me.

**Comment by Chandraprakash-Darji** [comment]
Thanks, @ctoffanin for raising the issue.  I assign the issue so we will love to have your contributions.

**Comment by mkubdev** [comment]
Hello @ctoffanin ! This is a super idea, thanks for spotting it! 😁
