### ISSUE TITLE
[BUG] Issue with Meta Tags and add Title

### ISSUE THREAD

**Issue by SirSimon162** [UniKonf/Vibey#196]
### Description of the bug

The meta tags in the _document.js file are using the `property` attribute instead of the `name` attribute for specifying the meta tag names. This inconsistency with the attribute name may be causing issues with the proper rendering of the meta tags for Twitter cards and Open Graph. The desired Twitter card banner and Open Graph image are not displayed properly when sharing the website URL on social media platforms.
Also, add a title.

### Please add screenshots (if applicable)

![vibey_before](https://github.com/UniKonf/vibey/assets/103681122/8cfe9877-a727-4d16-8e96-9b75f47db2a5)

PS: I would like to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Can you make me understand using some kind of illustrations?

**Comment by SirSimon162** [comment]
@Deepu178
Issue with Meta tag: The meta tags for Twitter cards and Open Graph should adhere to the HTML standard by utilizing the name attribute to define the meta tag names.
![meta](https://github.com/UniKonf/vibey/assets/103681122/72caaea7-bc83-4905-8808-48eb8b57aedd)
Using the incorrect attribute prevents the Twitter card from being displayed. Meta tags are important for search engine optimization (SEO) as they provide information about the website content.

Issue with title: 
The title should be 'Vibey'
![title](https://github.com/UniKonf/vibey/assets/103681122/5bb6caca-4e4b-41f2-84ce-eaa24936fbbf)
In the above screenshot you can see the difference between title of YouTube and Vibey. We should add a title tag with Vibey in it to display it.

**Comment by Deepu178** [comment]
@SirSimon162 You can start working on the issue.
