### ISSUE TITLE
Add [Perspektywy Women in Tech Summit 2023]

### ISSUE THREAD

**Issue by NehaKariya0309** [UniKonf/Vibey#200]
### Event Name

Perspektywy Women in Tech Summit

### Short Description of the Event ( 20 words )

The Perspektywy Women in Tech Summit is a prestigious event dedicated to empowering women in the field of technology. 

### Event Date and Time

14/06/2023 12:30 IST

### Event Page Link

https://womenintechsummit.pl/

### Themes

Artificial Intelligence, Quantum Computing, Semiconductors, Career Expo

### Facebook

https://www.facebook.com/perspektywy.wit/

### Instagram

https://www.instagram.com/perspektywy_women_in_tech/

### LinkedIn

https://www.linkedin.com/company/perspektywy-summit/

### Other Link

https://www.youtube.com/@DziewczynyNaPoliTV

**Comment by J-Harsh** [comment]
Hey, are you a part of GSSOC'23?

**Comment by NehaKariya0309** [comment]
@J-Harsh , yes I am a GSSoC'23 contributor

**Comment by J-Harsh** [comment]
Alright go ahead make the changes.
I have assigned you this issue

**Comment by vk20july** [comment]
@J-Harsh sir i want to work on this issue under gssoc'23
