### ISSUE TITLE
[Enhancement] Redesigning side menu on toggle in small screens

### ISSUE THREAD

**Issue by ujjawaltyagii** [UniKonf/Vibey#203]
- As of now the side-menu on small screens look a bit odd, so I would like to redesign it to give it a better and smooth look.

- I am a GSSoC23 contributor so please assign this issue under gssoc

### How it looks now :

![image](https://github.com/UniKonf/vibey/assets/115401171/34e97891-11e7-476a-816b-473d5d4f9c8d)

### How I plan to make it :

![image](https://github.com/UniKonf/vibey/assets/115401171/85d93812-85ca-4f38-8e9d-744b2184e86e)

#### *Any kind of feedback is appreciated

**Comment by ujjawaltyagii** [comment]
@J-Harsh could you please assign this issue to me

**Comment by Deepu178** [comment]
@ujjawaltyagii you are gonna make changes for smaller device?

**Comment by ujjawaltyagii** [comment]
@Deepu178 on large screen we have Nav bar which looks good and for small screen that nav bar turns into sidemenu which is basically a toggle menu. So i want to improve this toggle sidemenu.

**Comment by Deepu178** [comment]
Thanks for clarifying the issue and I'm assigning it to you. You can start working on this issue. @ujjawaltyagii
