### ISSUE TITLE
Want to change the border section color in website[FEATURE]

### ISSUE THREAD

**Issue by HimanshuNarware** [UniKonf/Vibey#204]
### Detailed description

I want to change the border section color on the website, I want to use blue and green colors instead of orange

### Context

Using blue and green color  match the theme of the website, improve the UI of the website, and I want to work on this issue

### Possible implementation

#screenshot
![22](https://github.com/UniKonf/vibey/assets/83147410/78e16016-0215-4d9b-a12a-19b40720ba12)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Hey, we do not want to change the color scheme of our website so feel free to find another enhancement. I am closing the issue for now.
