### ISSUE TITLE
[FEATURE] Ability to scrape from websites for CFPs'

### ISSUE THREAD

**Issue by roopeshsn** [UniKonf/Vibey#208]
### Detailed description

There are websites like https://seecfp.com/ to view CFPs'. This information can be scraped and rendered on the CFP page of vibey. 

### Context

This will be dynamic and require less manual updation of information. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@roopeshsn Good idea but can you explain a little bit in details how you are going to implement the function of scrapping the cfps from other websites

**Comment by roopeshsn** [comment]
Hey, I would like to leave this issue to the community!
