### ISSUE TITLE
Adding a About Us page.

### ISSUE THREAD

**Issue by Vishalk91-4** [UniKonf/Vibey#209]
I can add a about us section/ page and an contact us section preferably in the footer with like address, mail and support number

@J-Harsh could you please assign it to me under GSSOC23

**Comment by J-Harsh** [comment]
This very much sound like the other issue that you raised. 
Is there anything that I am missing?

**Comment by Vishalk91-4** [comment]
I thought of adding a page regarding About us the previous issue was of footer which would have just the link

**Comment by J-Harsh** [comment]
Alright, I am changing this issue to adding an about page only. You can make the other change regarding the footer in the other PR? Alright?

**Comment by Vishalk91-4** [comment]
Yes Sure, I'll make that in the other PR, and About in this one

**Comment by Vishalk91-4** [comment]
@J-Harsh can you tell me where do you want the about us page to be located

**Comment by Vishalk91-4** [comment]
I'm sorry If I'm not fixing the issue early, actually I've exams in my college , today or by tomorrow I'll fix both this and the footer issue

**Comment by Vishalk91-4** [comment]
@J-Harsh @Deepu178 
This is the how the page looks like do you want me to add testimonials section also, or it's fine, 
I'll change the images, and write the paragraph also 

About Section
![image](https://github.com/UniKonf/vibey/assets/116670999/d2640a8b-7422-4001-84e9-627ca17ef867)

**Comment by J-Harsh** [comment]
Hey, the screenshot if for the about us page right?
@Deepu178 can guide you on what can be the contents in the about us page.
Apart from that I would suggest to make the vibey's bg transparent if possible both in footer and in the hero image.

**Comment by Vishalk91-4** [comment]
@J-Harsh yes it's for about us page, 
Ok I'll make the Vibey background transparent, and since I have made PR for footer #233 also, so I'll change it there
@Deepu178 can you mention the other content so that I'll change them faster since it's weekend also

**Comment by J-Harsh** [comment]
If @Deepu178 does not respond you can go ahead with whatever you feel would be the right choice of words for our website.
You can start working on the issue

**Comment by Vishalk91-4** [comment]
@J-Harsh actually I've made the complete code for it, I'll just add content and update things in footer as well, and make a pull request by night
