### ISSUE TITLE
Enhancing the footer section 

### ISSUE THREAD

**Issue by Vishalk91-4** [UniKonf/Vibey#210]
The footer section can be improved with, the company logo with a tag line on left side and on the right side we can have a latest type section which lists the link of most recent events and hackathons about to happen, the company section and the social section

@J-Harsh could you please assign it to me under GSSOC23

**Comment by J-Harsh** [comment]
Hey, can you elaborate on what you mean by "type" section?
Your idea seems neat, just explain it a bit more and I will assign it to you

**Comment by Vishalk91-4** [comment]
@J-Harsh Okay so we can add a Latest Section which would have links to the next Most recent according to date, events, hackathons
This could redirect to the page where there would be detailed description about these

**Comment by J-Harsh** [comment]
Ok, I am assigning you this issue under the gssoc'23. Good luck working

**Comment by Vishalk91-4** [comment]
I 'll be adding the PR to this issue by today, sorry if it took time, my college exams are ongoing

**Comment by Vishalk91-4** [comment]
#233 fixes this, @J-Harsh could you please review it
