### ISSUE TITLE
[BUG] Links not working

### ISSUE THREAD

**Issue by parthpathakpp1** [UniKonf/Vibey#211]
### Description of the bug

When you click on particular event inside events page it does not take us to their official page instead it again redirect us to events page . I will add links of those events . So , when somebody click on the event it will get redirected to events official site. 

### Please add screenshots (if applicable)

https://github.com/UniKonf/vibey/assets/85991449/62d2e81a-e417-4d95-9b3b-78f8fa2b86ab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by J-Harsh** [comment]
@Deepu178 can you look into this one  on my behalf. Just ping me if you decide to assign the issue to @parthpathakpp1 I will do the rest

**Comment by parthpathakpp1** [comment]
> Collaborator

Hey @J-Harsh what about this ???

**Comment by J-Harsh** [comment]
Sure go ahead,you just need to add links to the cards.
I am assigning you this issue good luck have fun.

**Comment by parthpathakpp1** [comment]
> Sure go ahead,you just need to add links to the cards. I am assigning you this issue good luck have fun.

OK .
