### ISSUE TITLE
[FEATURE] Hackathon Page

### ISSUE THREAD

**Issue by parthpathakpp1** [UniKonf/Vibey#212]
### Detailed description

I will create full Hackathon page . 

### Context

It will help users to get information about upcoming hackathons and ongoing hackathons . 

### Possible implementation

I will add different hackathons in the page . 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by J-Harsh** [comment]
How are you planning to create a full fledged hackathon page? Where do you plan to get your data from?

**Comment by parthpathakpp1** [comment]
> How are you planning to create a full fledged hackathon page? Where do you plan to get your data from?

I am gonna make a separate js file where there will be all the hackathons data and gonna fetch it from that file and display it on the screen . .

**Comment by J-Harsh** [comment]
So we are currently using appwrite as a our backend that takes input from the users for hackathons and other forms of events. I would suggest you to have a look into it, and instead of just serving static data from a js file try integrating it with the backend as well, the above task can easily be a level 3 task if you are willing to integrate the backend as well i.e serving only the hackathons after filtering them out from the data received by the backend. If you think that is outside of your expertise, you can respond with the same and just build the UI of the about page

**Comment by parthpathakpp1** [comment]
> So we are currently using appwrite as a our backend that takes input from the users for hackathons and other forms of events. I would suggest you to have a look into it, and instead of just serving static data from a js file try integrating it with the backend as well, the above task can easily be a level 3 task if you are willing to integrate the backend as well i.e serving only the hackathons after filtering them out from the data received by the backend. If you think that is outside of your expertise, you can respond with the same and just build the UI of the about page

Will let you know in some time .

**Comment by parthpathakpp1** [comment]
> ou think that is outside o



> So we are currently using appwrite as a our backend that takes input from the users for hackathons and other forms of events. I would suggest you to have a look into it, and instead of just serving static data from a js file try integrating it with the backend as well, the above task can easily be a level 3 task if you are willing to integrate the backend as well i.e serving only the hackathons after filtering them out from the data received by the backend. If you think that is outside of your expertise, you can respond with the same and just build the UI of the about page

@J-Harsh I won't be able to do that but will build UI for about page .

**Comment by djv03** [comment]
hey, @parthpathakpp1 I can integrate backend with appwrite. we can co-authored this issue.you build UI I would make backend. let me know if you have started working on it? have made a branch for it?

**Comment by J-Harsh** [comment]
hey @parthpathakpp1 any update on the current issue? 
Did you have a chat with @djv03 about co-authoring on the issue?

**Comment by Deepu178** [comment]
@J-Harsh @parthpathakpp1 @djv03 
Any update on this issue?

**Comment by parthpathakpp1** [comment]
> @J-Harsh @parthpathakpp1 @djv03 Any update on this issue?

Will start working on it from today , My exams were going on .

**Comment by parthpathakpp1** [comment]
@djv03 Can you please share your discord id . We can connect over there .

**Comment by djv03** [comment]
djv#4191
hey @Deepu178 ,
after announcing transition of backend, how should I implement it, is there any guideline for  it?

**Comment by Deepu178** [comment]
@djv03 we are working on this issue on highest priority basis and hope to complete transition in one week. So after you will be able to extract database from MongoDB database. You can start working on this issue from next week. 
Untill then @parthpathakpp1 can work on client side.

**Comment by djv03** [comment]
> @djv03 we are working on this issue on highest priority basis and hope to complete transition in one week. So after you will be able to extract database from MongoDB database. You can start working on this issue from next week. Untill then @parthpathakpp1 can work on client side.

I think there is need of more specification and communication about schema and strucures of database. means there could be ambuguity in future if my understanding of project is differs from idea of project. I think we need either specification documents or one on one interaction for clarification of needs and demands.
