### ISSUE TITLE
[FEATURE] Add Alert

### ISSUE THREAD

**Issue by parthpathakpp1** [UniKonf/Vibey#213]
### Detailed description

When we Signup or  Signin it does not show any alert . Ex : "Registered Successfully" or "Registration failed" . 

https://github.com/UniKonf/vibey/assets/85991449/b219d838-ac89-4173-b212-334670d09b21

### Context

It will give idea to user that they registered or login successfully or did not . 

### Possible implementation

When information is right it will show alert and if information is wrong it will show alert .  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by J-Harsh** [comment]
I am assigning this issue to @parthpathakpp1 under GSSOC'23. Try to make a custom component with tailwindCSS without using any 3rd party tool as it would increase the size of the bundle and adhere to the contribution.md guidelines.

**Comment by parthpathakpp1** [comment]
> 

You mean to say I have to make alert by my own and can not use toastier and other third party modules . right ?

**Comment by J-Harsh** [comment]
Yes

**Comment by parthpathakpp1** [comment]
> Yes

got it

**Comment by djv03** [comment]
I think there could be conflict here. I have made PR which show alert by using react-toastify package. So, if @parthpathakpp1 made some changes in signup it would be conflicting with signup page. please share your thoughts here @J-Harsh

**Comment by J-Harsh** [comment]
@parthpathakpp1 hey any update on the given issue?
I think @djv03 is correct it might cause inconsistency in the code. 
If you haven't worked on the issue you can just react-toastify instead

**Comment by parthpathakpp1** [comment]
> @parthpathakpp1 hey any update on the given issue? I think @djv03 is correct it might cause inconsistency in the code. If you haven't worked on the issue you can just react-toastify instead

@J-Harsh okay will surely do that .

**Comment by djv03** [comment]
> > @parthpathakpp1 hey any update on the given issue? I think @djv03 is correct it might cause inconsistency in the code. If you haven't worked on the issue you can just react-toastify instead
> 
> @J-Harsh okay will surely do that .

what are you gonna do?
replace my changes with custom alerts or you telling me to do the same in signup??

**Comment by J-Harsh** [comment]
> > > @parthpathakpp1 hey any update on the given issue? I think @djv03 is correct it might cause inconsistency in the code. If you haven't worked on the issue you can just react-toastify instead
> > 
> > @J-Harsh okay will surely do that .
> 
> what are you gonna do?
> replace my changes with custom alerts or you telling me to do the same in signup??

We'll just go with react toastify for now.
You can just chill and contribute more 💐

**Comment by djv03** [comment]
> > > > @parthpathakpp1 hey any update on the given issue? I think @djv03 is correct it might cause inconsistency in the code. If you haven't worked on the issue you can just react-toastify instead
> > > 
> > > 
> > > @J-Harsh okay will surely do that .
> > 
> > 
> > what are you gonna do?
> > replace my changes with custom alerts or you telling me to do the same in signup??
> 
> We'll just go with react toastify for now. You can just chill and contribute more 💐

ok then. assign to me

**Comment by J-Harsh** [comment]
> > > > > @parthpathakpp1 hey any update on the given issue? I think @djv03 is correct it might cause inconsistency in the code. If you haven't worked on the issue you can just react-toastify instead
> > > > 
> > > > 
> > > > @J-Harsh okay will surely do that .
> > > 
> > > 
> > > what are you gonna do?
> > > replace my changes with custom alerts or you telling me to do the same in signup??
> > 
> > We'll just go with react toastify for now. You can just chill and contribute more 💐
> 
> ok then. assign to me 

Your pr is already merged if I'm not mistaken, and this issue is already assigned to someone else. 
Feel free to look for other ways of contributions.

**Comment by Deepu178** [comment]
@J-Harsh should we close this issue?

**Comment by J-Harsh** [comment]
Yes
