### ISSUE TITLE
[BUG] Navbar

### ISSUE THREAD

**Issue by arin-paliwal** [UniKonf/Vibey#216]
### Description of the bug

# Issue: Non-transparent Navbar when Not Scrolled

## Description
Currently, the navbar on the website remains opaque (non-transparent) even when the page is not scrolled. It would be visually appealing and consistent with modern design practices if the navbar were transparent when the page is not scrolled and became opaque only when the user starts scrolling.

## Steps to Reproduce
1. Open the website/application.
2. Observe the navbar without scrolling.

## Expected Behavior
The navbar should have a transparent background when the page is not scrolled.

## Actual Behavior
Currently, the navbar remains opaque regardless of whether the page is scrolled or not.

## Possible Solution
Implement a CSS or JavaScript functionality that makes the navbar transparent when the page is not scrolled and changes it to an opaque background only when the user starts scrolling.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
We want the background of our navbar to be a bit transparent, that is a conscious design choice. The navbar is working as expected and therefore I am closing this issue feel free to find other ways to contribute.
