### ISSUE TITLE
ADD[Google Girl Hackathon]

### ISSUE THREAD

**Issue by VC6378** [UniKonf/Vibey#218]
### Event Name

Google Girl Hackathon

### Short Description of the Event ( 20 words )

Girl Hackathon is a program for women students in computer science and allied courses across India.

It has been designed to provide a platform for women in the engineering campus space to showcase their coding skills and promote creative solutions for real-time technical challenges. This virtual hackathon will challenge the innovation and problem-solving skills of the participants and inspire them to creatively engage with Google. 

### Event Date and Time

28/05/2023

### Event Page Link

https://rsvp.withgoogle.com/events/girl-hackathon-2023/home

### Themes

Hackathon

**Comment by VC6378** [comment]
@J-Harsh please assign me this issue, I am interested to contribute in this issue.

**Comment by VC6378** [comment]
@mkubdev please assign me this issue, I am interested in contributing to this issue.

**Comment by J-Harsh** [comment]
Hey @VC6378 are you a part of gssoc?

**Comment by Snigdha2712** [comment]
Please assign this project to me. i will fix the issue

**Comment by J-Harsh** [comment]
> Please assign this project to me. i will fix the issue

if @VC6378 doe not reply then sure

**Comment by VC6378** [comment]
@J-Harsh Yes i am part of GGSoC'23.

**Comment by J-Harsh** [comment]
Please mention it in future issues.
I'm assigning you the issue.
Good luck have fun contributing

**Comment by Deepu178** [comment]
@VC6378 any update about the issue?

**Comment by VC6378** [comment]
@Deepu178 this event has passed now :(
