### ISSUE TITLE
Add OPEN SOURCE EVENT

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [UniKonf/Vibey#219]
### Event Name

ASIA’S LEADING OPEN SOURCE EVENT

### Short Description of the Event ( 20 words )

Open Source India (OSI) is an attempt by the team at Open Source For You magazine in partnership with India’s Open Source community and industry—to bring various stake-holders under one roof.

### Event Date and Time

12-13 October 2023

### Event Page Link

https://www.opensourceindia.in/

### Themes

Open Source

**Comment by J-Harsh** [comment]
You want to add an event right?

**Comment by Shiva-Sai-ssb** [comment]
> You want to add an event right?

Yes. Can you assign me?

**Comment by J-Harsh** [comment]
Yes sure.
I am assigning you this issue under GSSOC'23. 
Good luck and have fun contributing

**Comment by Shiva-Sai-ssb** [comment]
> Yes sure. I am assigning you this issue under GSSOC'23. Good luck and have fun contributing

Thanks. To clarify, I'm not working under GSSOC'23, you can remove the label.

**Comment by J-Harsh** [comment]
Thanks a lot for clarifying.
Have fun contributing <3
