### ISSUE TITLE
[BUG] <JSConf india 2023 not redirecting to JSConf website>

### ISSUE THREAD

**Issue by kedar1998** [UniKonf/Vibey#226]
### Description of the bug

When clicked on JSConf india 2023. It is redirecting to itself. I will redirect link to https://jsconf.in/ and it will open in new tab. Can you please assign this issue to me under GSSOC'23.

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/103363619/85badf52-79a4-402c-bca1-5e08af684780)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by djv03** [comment]
hey @kedar1998 , are u working on it? if not I am taking it

**Comment by kedar1998** [comment]
I am working on it

**Comment by kedar1998** [comment]
@J-Harsh can you assign this issue to me under GSSOC' 23

**Comment by J-Harsh** [comment]
hey @kedar1998 @djv03 I think there is already an issue on broken link and work is in progress. Since this is a duplicate issue I will be closing this
