### ISSUE TITLE
[BUG] <bug description> google sign redirecting to home page

### ISSUE THREAD

**Issue by djv03** [UniKonf/Vibey#228]
### Description of the bug

google sign redirecting to home page

### Please add screenshots (if applicable)

![Screenshot 2023-05-31 091118](https://github.com/UniKonf/vibey/assets/93385841/bd25af67-cb31-4a28-be1c-10f3edc54833)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
hey @djv03 how do plan to implement googe sign in?

**Comment by djv03** [comment]
I will use firebase for fetching user profile and name. 

it would also change the UI, get started would dissapear and personal info of user would be displayed:
