### ISSUE TITLE
💡 [FEATURE]: ACCESSIBILE SOCIAL ANCHORS ON FOOTER, HEADER, AND EVENT CARD

### ISSUE THREAD

**Issue by 0xabdulkhaliq** [UniKonf/Vibey#229]
### Description

- This issue is about adding `aria-label` for social anchors (links like Github) which are placed inside the `footer` element

- it is important to note that we want to add the `title` attribute also. This is because the `title` attribute is intended to provide additional information to screen reader users.

- The `aria-label` attribute is a way more important for providing accessibility information to screen reader users. The `aria-label` attribute is an Accessible Rich Internet Applications (ARIA) attribute that can be used to provide a label for an element. This label is then read aloud by screen readers, providing additional information about the element to the user.

- In general, the `aria-label` & `title` attributes are preferred for providing accessibility information to screen reader users.

- You can consider to assign this issue to me to make the site accessible for screen readers

### Code of Conduct

- [X] I have checked the existing issues
- [X] I agree to follow this project's Code of Conduct
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by mkubdev** [comment]
Hello @0xabdulkhalid 👋🏻 ! That's great to you to propose A11y optimisation. 🤝
I assign you
