### ISSUE TITLE
[FEATURE] Adding 'Contact Us' Page

### ISSUE THREAD

**Issue by dhingra-madhav** [UniKonf/Vibey#232]
### Detailed description

Hi @J-Harsh
While exploring the website, I noticed that on clicking 'Contact' button, we get a 404-Page Not Found page.
Being a GSSoC'23 contributor, I would like to create the 'Contact Us' page. So, can you please assign this to me under GSSoC'23 ?

![image](https://github.com/UniKonf/vibey/assets/114823435/82789d67-a085-4170-b4c3-f451004dbf4a)

### Context

According to me, 'Contact Us' page plays a significant role for a website as it can serve as a means of direct communication between the end users and the website maintainers. Moreover, the users can report bugs or issues encountered by them. Also, they can give feedback for the improvement of the website.

### Possible implementation

Using TypeScript

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Hey, what do you plan to include in the contact page? 
We are already working on building an about us page, how do you plan to differentiate between the two?

**Comment by dhingra-madhav** [comment]
As per my plan, the contact page will consist of 2 sections:
1. Enquiry form: Through this form, the users (if they wish) can enquire more about any upcoming event or hackathon. It will also include the social media handles of Vibey.
2. Event/Hackathon addition form: Through this form, the event organizers or hackathon organizers can request to the Vibey team about their upcoming event/hackathon to be listed on Vibey Website.

Note: The mail address to which each form will send its data would be different in above two forms so as to handle things separately and properly.

The 'About Us' page that you are already working on will consist of details about founder, team members, mission and vision etc. However, the 'Contact Us' page will serve as a means to get in touch with the Vibey team regarding posting of any upcoming event/hackathon or any enquiry for the same.

**Comment by J-Harsh** [comment]
We have a proper pipeline of contribution that allows users to add their own events.
Furthermore, isn't the entire purpose of the website is to be a one stop destination for all the events etc?
We currently at Vibey do not provide any customer support or queries regarding events

**Comment by dhingra-madhav** [comment]
Okay.

**Comment by dhingra-madhav** [comment]
Okay.
