### ISSUE TITLE
[BUG] : Repetition in Upcoming Events

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#235]
### Description of the bug

There is a repetition on the upcoming events page.

![image](https://github.com/UniKonf/vibey/assets/62666287/7d963636-3f10-462a-8163-0873c507e2ef)

![image](https://github.com/UniKonf/vibey/assets/62666287/724b674b-e919-4387-bb0f-5875fbb87c9b)

I would like to work on it under GSSOC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Sure, go ahead and work on it. I am assigning you this issue under the GSSOC'23.
