### ISSUE TITLE
[FEATURE] Create dynamic page for `themes` member to filter events by theme

### ISSUE THREAD

**Issue by mkubdev** [UniKonf/Vibey#24]
### Detailed description

* use the `themes` field to create dynamic page to filter all events related the one category.

For example: 
- I go to `/events/themes/devops` and we filter all events with the tag `devops`

### Context

This is not important right now, as this can be quickly implemented.

### Possible implementation

* using next.js page folder structure

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ctoffanin** [comment]
Hello peeps! If you are not planning to assign this to anybody else, you can drop it on me if you want.

**Comment by Chandraprakash-Darji** [comment]
It is great seeing you again here @ctoffanin. Sure you can create I assign you the issue

**Comment by ctoffanin** [comment]
Hello, I want to tell you I'm not MIA. I had a couple of busy weeks/weekends.
I wanted to ask if you could elaborate more on your expectations of this issue.

**Comment by mkubdev** [comment]
> Hello, I want to tell you I'm not MIA. I had a couple of busy weeks/weekends. I wanted to ask if you could elaborate more on your expectations of this issue.

Hi, no problem at all. I think we are all in the same situation.. 🎄
> I wanted to ask if you could elaborate more on your expectations of this issue.

Sure, we to achieve to filter the events by `themes`. Actually, the [`EventInterface`](https://github.com/WebXDAO/DevConf/blob/main/src/lib/types.ts) had a `themes` member that can be used to create dynamic page. (It's an array of string)

Then, from a filtering component or from a dynamic page like `/events/theme/<theme>` where we request/filter the whole events dataset.
This issue is too open, i will update it to be more precise.

**Comment by ctoffanin** [comment]
Hey everybody, I'm pretty busy lately.
I'm not sure when I can pick this up, and I don't want to hold the issue hostage.
For now, I'm going to unassign myself from it, so it will be available for somebody else to work on it.
Sorry for taking so long :)

**Comment by hariscs** [comment]
hey @ctoffanin i got this, i can work on it
