### ISSUE TITLE
Improve Readme: Make it More Descriptive and Beginner-Friendly

### ISSUE THREAD

**Issue by Devarsh009** [UniKonf/Vibey#240]
### Detailed description

I noticed that the current README of the Vibey project could benefit from improvements to make it more descriptive and beginner-friendly. As someone interested in the project, I believe a clearer and more informative README will help users better understand the concept of Vibey and encourage their participation. 

Thank you for considering this enhancement to the project's README. I look forward to contributing to the success of Vibey.

Ps:- Please assign me this issue under Gssoc contributos label.

### Context

By making these improvements, we can make the Vibey project more approachable and welcoming to beginners, leading to increased contributions and overall growth of project Vibey.

### Possible implementation

Here are a few suggestions to enhance the README:

1. Provide a brief overview of Vibey's purpose and key features at the beginning.
2. Include a step-by-step guide on how to set up the project locally for new contributors.
3. Add a section explaining the project structure and organization to aid developers in navigating the codebase.
4. Highlight the different areas where contributors can make valuable contributions (e.g:- UI/UX, documentation, bug fixing).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Devarsh2117 Thanks for raising an important issue about documentation and explaining it how you will be doing it. I'm assigning this issue under GSSoC. Enjoy working on the issue.

**Comment by Deepu178** [comment]
@Devarsh2117 any update on this issue?
