### ISSUE TITLE
[FEATURE] Add About Us Page

### ISSUE THREAD

**Issue by PatilHarshh** [UniKonf/Vibey#242]
### Detailed description

This seems that website not contain about us page . if about page is added then it will tell breif about website which is helpful for users @J-Harsh 
![Screenshot (79)](https://github.com/UniKonf/vibey/assets/120102234/8b24f4da-d21e-4b41-a9a9-e4d7d79950dd)

### Context

this increase user experience

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Hey, an about us page is in the works. 
Feel free to look at other open issues or create your own
