### ISSUE TITLE
[FEATURE] : Custom scrollbar for light theme

### ISSUE THREAD

**Issue by ujjawaltyagii** [UniKonf/Vibey#244]
#### As of now "Vibey" have a scroll-bar with custom design but it's color components are same for both `Light Theme` and `Dark Theme` , the current scroll bar looks good in dark theme but its not matching and suiting light theme.

So : 
1. I plan to add custom scroll-bar for light theme
2. I plan to add hover effect on scrollbar so whenever a user hovers the scrollbar it will have a color effect to make it more visually appealling.

### Context

https://github.com/UniKonf/vibey/assets/115401171/f4df78ca-fecb-479c-be3c-cf38e290aa5e

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Sure @ujjawaltyagii go ahead.
I'm assigning you the issue

**Comment by Deepu178** [comment]
We have recently changed our theme that's why I'm closing this issue
