### ISSUE TITLE
[BUG] Improper spacing between cards, repetition and improper arrangement of cards

### ISSUE THREAD

**Issue by smty2018** [UniKonf/Vibey#247]
### Description of the bug

Improper spacing between cards, repetition and improper arrangement of cards

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/74114936/caa96fc0-daad-4d1f-a60f-b8de5203c84a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
this issue has already been resolved.
