### ISSUE TITLE
Remove yarn.lock file from the codebase

### ISSUE THREAD

**Issue by Deepu178** [UniKonf/Vibey#250]
Add the yarn.lock file in .gitignore so contributors can install the dependencies using any package manager.

**Comment by tanishqamitra** [comment]
Hi! @Deepu178
I would like to work on this issue under gssoc and please assign the issue so I can start working on this issue

**Comment by Deepu178** [comment]
Hi! @tanishqamitra 
I have assigned the issue and you can start working on this issue.
