### ISSUE TITLE
[BUG] Text Visibility Issue on Privacy and Terms Page in Light Mode

### ISSUE THREAD

**Issue by Rohan3011** [UniKonf/Vibey#259]
### Description of the bug

Text Visibility Issue on Privacy and Terms Page in Light Mode.
I'm GSSOC contributor and I'd like to work on this issue.

### Please add screenshots (if applicable)

![Screenshot 2023-06-09 121749](https://github.com/UniKonf/vibey/assets/76813454/393e9886-2ba5-46bc-a738-d4e4c76178f8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by J-Harsh** [comment]
Hey @Rohan3011 I am assigning you the issue under GSSOC'23, have fun contributing.
