### ISSUE TITLE
Add [She Builds Meetup] upcoming event 

### ISSUE THREAD

**Issue by ManishaSwain8** [UniKonf/Vibey#260]
### Event Name

She Builds Meetup

### Short Description of the Event ( 20 words )

SheBuilds is a leading organization committed to promoting gender diversity and equity in technology. We believe that everyone, regardless of gender, should have the opportunity to excel in tech.

### Event Date and Time

10/6/23 

### Event Page Link

https://www.shebuilds.tech/

### Themes

Hackathon

**Comment by Deepu178** [comment]
@ManishaSwain8 thanks for creating issue and I think this meet up is over so it will not be making any sense if we add this meet up to the platform
Feel free to look into other issues or creating new issues.

**Comment by ManishaSwain8** [comment]
yeah it's over already,  : |)
