### ISSUE TITLE
Back to top button.

### ISSUE THREAD

**Issue by medhacodes** [UniKonf/Vibey#261]
### Detailed description

Add a beautiful and smooth back-to-top button. 

### Context

It would be easier to scroll up and get to the top of the page just by clicking a button. A back-to-top button is a basic feature of website.

### Additional information

Please assign this issue to me..

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@medhacodes I think it should be used when you have too much content on home page but I don't think we have too much content on homepage so this implementation will not be very useful and I am closing this issue for now if you like to contribute to other issues or just want to create more issues you can do that. 
Thanks

**Comment by medhacodes** [comment]
Sure thanks!
