### ISSUE TITLE
Shift the backend from Appwrite to Node.js and MongoDB

### ISSUE THREAD

**Issue by Deepu178** [UniKonf/Vibey#262]
We are shifting the backend from Appwrite to Node.js

This transition to Node.js will bring us more flexibility, control, and improve the overall performance and scalability of Project Vibey. Here are the key points: 

Improved Flexibility: With Node.js, we'll have a wide range of libraries and tools to customize our backend according to our needs.

Increased Performance: By leveraging Node.js's event-driven, non-blocking architecture, we'll see a significant boost in Project Vibey's performance and responsiveness. 

Easier Integration: Node.js offers extensive support for frameworks and modules, making it a breeze to integrate with other systems and services seamlessly.

**Comment by suzy-g38** [comment]
Can I work on this issue under gssoc23?

**Comment by Deepu178** [comment]
@suzy-g38 I have assigned the issue. Please enjoy working on the issue and let's make some good improvements to the project.
