### ISSUE TITLE
[FEATURE] Contact and About page

### ISSUE THREAD

**Issue by Spruha017** [UniKonf/Vibey#263]
### Detailed description

I can create  Contact and About page . Assign this to me under GSSOC'23

### Context

Currently on clicking the contact and about at the end of the page it leads to 404 error .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Thanks for creating the issue @Spruha017 we have already created the page of about us and you can create the page of contact us.
