### ISSUE TITLE
[Bug]: Menu icon not properly aligned on mobile screen devices.

### ISSUE THREAD

**Issue by harmeetsingh11** [UniKonf/Vibey#264]
**Description**
The menu icon is not properly aligned on mobile screens. It should be right aligned.

**Screenshots**
![Screenshot_20230611-012533_Chrome.png](https://github.com/UniKonf/vibey/assets/130365071/b5372e1b-2b43-4ae2-8520-c2a73cb0b3a1)

**Record**
- [x] I agree to follow Code of conduct and Contribution guidelines.
- [x] I'm a GSSoC'23 contributor.

Please assign me this issue under GSSoC'23.
Thanks

**Comment by Deepu178** [comment]
@harmeetsingh11 I'm assigning this issue under GSSoC. Enjoy contributing to the project!
