### ISSUE TITLE
[FEATURE] Improve the UI of subscribe section

### ISSUE THREAD

**Issue by sumitkr2000** [UniKonf/Vibey#265]
### Detailed description

The UI of subscribe section is not looking good. Please assign me this issue. Thank you!

![image](https://github.com/UniKonf/vibey/assets/100675296/20309b5e-7e44-4c4f-9f03-7d40310636f6)

### Context

This is very important

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohdhaider07** [comment]
assign this to me

**Comment by Deepu178** [comment]
@sumitkr2000 Thanks for creating the issue as we were also looking for improvement in subscribe section. I am assigning this issue and let make it more visually appealing to the users. Enjoy contributing to the project.
Are you contributing under GSSoC.

**Comment by sumitkr2000** [comment]
yeah sure @Deepu178 !

**Comment by sumitkr2000** [comment]
Hello, @Deepu178 is this ok?

[screen-capture.webm](https://github.com/UniKonf/vibey/assets/100675296/5def9df1-f6b3-405c-81e3-797aba7ed72a)

**Comment by Deepu178** [comment]
@sumitkr2000, I would suggest you to align the fields horizontally in larger screens and for a smaller screens you can use the flex column to align the fields in vertically but in case of larger screens you can make all the fields horizontally by taking some gap.

**Comment by sumitkr2000** [comment]
Okay bro as you say. I will apply the changes! @Deepu178

**Comment by sumitkr2000** [comment]
Now is it good?

- Large device:-

![image](https://github.com/UniKonf/vibey/assets/100675296/fa50a49a-4e62-4715-bd11-307d321de52c)

- Medium device:-

![image](https://github.com/UniKonf/vibey/assets/100675296/84324d06-bcfa-43ee-80ab-908d91ab6358)

- Small device:-

![image](https://github.com/UniKonf/vibey/assets/100675296/730ad67a-2e5a-4b54-97bc-7495ff60f635)

**Comment by sumitkr2000** [comment]
@Deepu178 Please review this.

**Comment by sumitkr2000** [comment]
@Deepu178 Bro please review this. I have to make pr.

**Comment by Deepu178** [comment]
It looks good and can you add outline if user writes something into input field. This is ready for pr, please go ahead!

**Comment by sumitkr2000** [comment]
@Deepu178 Yeah I can add it.

**Comment by sumitkr2000** [comment]
@Deepu178 Now is it good?

![image](https://github.com/UniKonf/vibey/assets/100675296/8aef8c3e-c0ce-4784-a6ad-cb99f2498513)
