### ISSUE TITLE
[ENHANCEMENT] <logo visibility issue in navbar while in light mode>

### ISSUE THREAD

**Issue by Not-Sarthak** [UniKonf/Vibey#266]
### Description of the bug

The color of logo and navbar seems to blend within each other

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/92942966/e0a60b76-78b0-4492-b8c3-c55f7f332709)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Varghab** [comment]
@Deepu178 Please assign me this issue, I can fix this.
