### ISSUE TITLE
[FEATURE] Menu bar redesign

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#267]
### Detailed description

Hey, 
I already designed a Menubar previously, and the PR got merged but is not reflected on the main site. I can again redesign the menu bar and give it a sleek look. 

I am leaving some screenshots of my previous work for the menubar - 
![navbar_new_dark](https://github.com/UniKonf/vibey/assets/59419650/222da268-8957-40e5-a5b1-de7cbd20b654)
![navbar_new_light](https://github.com/UniKonf/vibey/assets/59419650/75aba01b-8181-4cbb-ac07-7a7ccc64ae40)

### Context

The current menubar design looks average and I believe I can turn the menubar into an elegant one.
**This is important to me because the current Menubar looks inconsistent with respect to the overall design of the website.** 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab your pr had some errors which was failing in deployment so needed to revert it back. You can create again pr for this but I would suggest you to put "Get Started" outside menu.

**Comment by Varghab** [comment]
@Deepu178 Okay, I will create a new menubar then, please assign me this under GSSoC'23

**Comment by Deepu178** [comment]
@Varghab I have assigned this issue and please make sure that "Get Started" button remains outside the menu bar. Enjoy working on the issue.

**Comment by Varghab** [comment]
@Deepu178 Is it necessary to keep the "Get Started" button out of the menu bar? Because currently it is still there in the menu bar, but we can't see this as there is no bg set. I am attaching a SS, please have a look at this. Actually, I am thinking to creating something like the video I have attached.

![Screenshot 2023-06-16 005806](https://github.com/UniKonf/vibey/assets/59419650/6e2d8698-1e02-41c1-b3b9-c4ae0e2a36bb)

https://github.com/UniKonf/vibey/assets/59419650/921c65e2-9a04-4874-bc19-78c46335087f

**Comment by Deepu178** [comment]
@Varghab that looks nice and just take care of bg and text colours. I'm suggesting to put "Get Started" outside menu bar for smaller screens as it will be good idea. Please go ahead with it 🚀🚀
