### ISSUE TITLE
[BUG] Iconsistent footer design

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#268]
### Description of the bug

The color theme of the footer is inconsistent as compared to the rest of the site. The current color used in the footer section is "Light Orange", but on other areas of the website "Light Hot Pink," kind of color is used. 
![Screenshot 2023-06-12 131114](https://github.com/UniKonf/vibey/assets/59419650/f6657a61-4d4f-4300-9c25-a5687ec72084)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab what colour combination you are gonna use to make it more consistent throughout the footer?

**Comment by Varghab** [comment]
@Deepu178 Changing the footer link's color to baby hot pink would make more sense as the other sections of the site are using the same color. I am also thinking to add icons under the 'Socials' section in the footer, which would be more compelling. Please assign me the issue under GSSoC'23 if you think my idea is relevant.

**Comment by tanishqamitra** [comment]
Hii @Deepu178  I would like to work on this issue under GSSOC'23 and please assign the issue so I can start working on this issue.

**Comment by Deepu178** [comment]
@Varghab would you like to work on this issue? Or should I assign the issue to @tanishqamitra 
As you have been already assigned two issues so you need to create pr for that before getting assigned this issue.

**Comment by Varghab** [comment]
@Deepu178 Yes, I want to work on this. It wouldn't take much time to solve this issue.

**Comment by Deepu178** [comment]
@Varghab I'm assigning this issue and looking forward to reivew your pr.
