### ISSUE TITLE
[FEATURE] : Adding auto-assign github workflow to PR

### ISSUE THREAD

**Issue by ujjawaltyagii** [UniKonf/Vibey#271]
### Detailed description

As of now, whenever a PR is opened by a contributor then either the pull request needs to be assigned with "assignee" `manually` or it goes `unassigned`.

However we can <b>automate this step, so whenever someone opens a PR then that PR will be automatically assigned to that person</b>

- It will reduce the burden of maintainers

### Context

![image](https://github.com/UniKonf/vibey/assets/115401171/000f9457-c954-4c26-ac37-acd2ffc55a98)

### Possible implementation

- I will add this functionality with proper conventions using GitHub Actions in .yml file

### Additional information

I'm a gssoc contributor so please assign me this issue under gssoc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ujjawaltyagii** [comment]
@J-Harsh @Deepu178 please assign me this issue

**Comment by Deepu178** [comment]
@ujjawaltyagii I'm assigning this issue under GSSoC. Enjoy working on this issue.
