### ISSUE TITLE
[IMPROVEMENT] Correct The Grammar In The Tagline

### ISSUE THREAD

**Issue by Arcodex9** [UniKonf/Vibey#272]
Your tagline has a grammatical error.

This is your slogan(tagline):
⇒ All the online conference, workshop & events at one place.

It should be like this:
⇒ All online conferences, workshops & events at one place.

Or, you can use this instead.
⇒ Online conferences, workshops & events all in one place.

Like:
All the online ⇔ Online conferences
conference, workshop & events ⇔ workshops & events
at one place. ⇔ all in one place.

It'll look cleaner and more appealing.
Thanks

**Comment by tanishqamitra** [comment]
Hi! @Deepu178 
I would like to work on this issue under GSSOC'23 and please assign the issue so I can start working on this issue.

**Comment by Deepu178** [comment]
Hiii @tanishqamitra 
I have assigned this issue and added labels for GSSoC. I hope you enjoy contributing to the project under GSSoC and waiting for reviewing your pr 🚀

**Comment by Deepu178** [comment]
Thanks @tanishqamitra for making contribution to the project and looking forward for reviewing more pr under GSSoC 🚀
