### ISSUE TITLE
Seprate section for event not happend and happend.

### ISSUE THREAD

**Issue by bakshiyogesh** [UniKonf/Vibey#275]
### Detailed description

![image](https://github.com/UniKonf/vibey/assets/83563027/5f6ee4bf-921d-4aa8-902c-5abb615e19e0)

### Context

So it users can see upcoming events. As it is showing which events were happend in upcoming events.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@yogesh784, it's a really good feature to implement but can  you please tell me in details that how would you implement this feature?

**Comment by bakshiyogesh** [comment]
@Deepu178 Firstly thanks for replying.I want to say that as in picture above the event which was happend in past it is showing in upcoming events section.If we could declare a another section for Event happend/Past.for that as example- if a event is not happend yet it displayed in upcoming section of events and if a event happend that would dispatch to Event happend section and if any event would not going to happen then that section empty with remarks that events would display here of future.
or we could add  check which would determine if event date passed so that it would disappear from upcoming section and shown in events happend section.

**Comment by Deepu178** [comment]
@yogesh784 got your point and I think using dates will be the right option for disappearing the events from upcoming section. Do you want to work on this issue?

**Comment by bakshiyogesh** [comment]
@Deepu178  Yes i want to work on this issue and learn by doing.Is there used any state management library.

**Comment by Deepu178** [comment]
@yogesh784 I am assigning this issue and enjoy working on the issue. waiting to review your pr.
Are you contributing under GSSoC?

**Comment by bakshiyogesh** [comment]
@Deepu178 No i'm not contributing under GSSoC.

**Comment by Deepu178** [comment]
@yogesh784 sure, looking forward to review your pr.

**Comment by Deepu178** [comment]
@bakshiyogesh  Any update  on the issue?

**Comment by bakshiyogesh** [comment]
Yes @Deepu178 another one change that event manually but i was thinking how could we can  implement something so the when event date pass
it which event was happend goes and next one uploaded dynamically.
could you suggest me any idea about it.

**Comment by Deepu178** [comment]
@bakshiyogesh I am closing this issue for now coz we are not looking to implement it rn. thanks for creating the issue and really appreciate it.
