### ISSUE TITLE
[ADD] Tata Women of Mettle 2023

### ISSUE THREAD

**Issue by VC6378** [UniKonf/Vibey#278]
### Event Name

Women of Mettle 2023

### Short Description of the Event ( 20 words )

Women Of Mettle is among the various campus connect programs introduced by Tata Steel that are aimed at encouraging bright young minds in engineering and management institutes to hone their intellect in areas such as research & development, operational excellence, business strategy, and management, etc. The idea is to foster a collaborative environment among students, academia, and the corporate sector and provide unique and aspiring career opportunities to the young talent of India.

### Event Date and Time

01/07/2023

### Event Page Link

https://xathon.mettl.com/event/women-of-mettle-2023

### Themes

WEB DEVELOPMENT,HACKATHON

**Comment by Deepu178** [comment]
@VC6378 thanks for creating the issue and do you want contribute to vibey through this issue?
Are you contributing under GSSoC?

**Comment by VC6378** [comment]
@Deepu178  Yes sir

**Comment by Deepu178** [comment]
@VC6378 I have assigned the issue under GSSoC  and enjoy working on this issue. 🚀
