### ISSUE TITLE
Add Builders Hub: BuidlWithUs

### ISSUE THREAD

**Issue by tanishqamitra** [UniKonf/Vibey#281]
### Event Name

Builders Hub: BuidlWithUs

### Short Description of the Event ( 20 words )

Connect, collaborate, and innovate in blockchain and cryptocurrency projects. Builders Hub: BuidlWithUs is a platform for decentralized development.

### Event Date and Time

Saturday, June 24  2:30 PM to 6:00 PM

### Event Page Link

https://lu.ma/BuildersHub-BuidlWithUs?tk=kCG4Ok

### Themes

BLOCKCHAIN & CRYPTOCURRENCY

### Facebook

NA

### Github

NA

### Instagram

NA

### LinkedIn

NA

### Twitter

NA

### Discord

NA

### Other Link

NA

**Comment by tanishqamitra** [comment]
Hi! @Deepu178
I would like to work on this issue under GSSOC'23 and please assign the issue so I can start working on this issue.

**Comment by Deepu178** [comment]
Hii @tanishqamitra , I'm assigning this issue under GSSoC and looking forward to review your pr. Enjoy working on this issue 🚀
