### ISSUE TITLE
Add Events(Builders Hub, International React Conf, Web3 Conf, Civo Navigate, International JavaScript Conf, React India)

### ISSUE THREAD

**Issue by tanishqamitra** [UniKonf/Vibey#285]
I just want to add these popular events which are going to happen soon. So I would like to work on this issue and please assign this issue under GSSOC'23.

**Comment by Deepu178** [comment]
Hiii @tanishqamitra
I have assigned this issue and added labels for GSSoC. I hope you enjoy contributing to the project under GSSoC and waiting for reviewing your pr 🚀
