### ISSUE TITLE
[BUG] <Update Sidebar Design for Mobile View>

### ISSUE THREAD

**Issue by manaver** [UniKonf/Vibey#289]
### Description of the bug

Currently, the sidebar displays buttons for various sections like events, CFPs, and Hackathons.

The suggested update involves replacing the buttons with text links. When hovering over these text links, a thick bottom border should appear to provide a visual indicator to users. This will help users easily identify the active section and navigate through the content.

Additionally, the "Get Started" button needs to be centered within the sidebar to enhance its visibility and ensure a balanced layout.

### Please add screenshots (if applicable)

[Screencast from 17-06-23 12:53:46 PM IST.webm](https://github.com/UniKonf/vibey/assets/78682260/d9dfbd57-d305-4e3c-83b5-beed8e5a67be)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manaver** [comment]
I am a gssoc'23 contributor please assign this issue to me. I'd love to work on this issue.
Thanks!

**Comment by Deepu178** [comment]
This issue has already been resolved
