### ISSUE TITLE
Changing the color of the card on hovering

### ISSUE THREAD

**Issue by tanishqamitra** [UniKonf/Vibey#291]
### Detailed description

We should change the color of the card on hover from orange to according to the theme 

### Context

It will look good to the user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@tanishqamitra Thanks for creating the issue!
Do you wanna work on this issue and are you contributing under GSSoC?

**Comment by devmusiczz** [comment]
@Deepu178 I want to work on this issue and I am contributing under GSSoC. Please assign this issue to me.

**Comment by tanishqamitra** [comment]
Yes @Deepu178 I would like to work on this issue and I'm contributing under GSSoC.

**Comment by Deepu178** [comment]
@tanishqamitra I have assigned the issue and added labels to it. Enjoy contributing to the project 🚀🚀
