### ISSUE TITLE
[Make locations name under filter button more beautiful.]

### ISSUE THREAD

**Issue by akshaysoni10** [UniKonf/Vibey#292]
### Detailed description

Under filter button, all locations names are so simple. I want to make more beautiful using styling.

### Context

It's looks attractive to users.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Thanks @akshaysoni10  for creating the issue! Can you explained in details about this and what kind of combination of colors and styling you are going to use to make it more visually appealing.

**Comment by akshaysoni10** [comment]
I just want to make it like a button with text and background color and add styling like Get started button.

**Comment by Nainish-Rai** [comment]
Hii , I made a pull request and linked the issue

**Comment by akshaysoni10** [comment]
@Nainish-Rai Have you raised the same issue before.

**Comment by Nainish-Rai** [comment]
@akshaysoni10 Since, No one was assigned this issue I thought that I can complete and make a pull request.

**Comment by Nainish-Rai** [comment]
can you please assign it now?

**Comment by akshaysoni10** [comment]
@Nainish-Rai You cannot make and merge any PR until the issue is assigned to you.

**Comment by akshaysoni10** [comment]
@Deepu178 Can you please assign me this task under GSSoC'23.

**Comment by Deepu178** [comment]
@akshaysoni10  Why do you think it should be button and not checkbox type element for locations? What are your thoughts on this?

**Comment by akshaysoni10** [comment]
Checkbox is a good option. We can implement it.

**Comment by Deepu178** [comment]
@akshaysoni10 
I'm assigning this issue under GSSoC and waiting to review your pr for the project.

**Comment by akshaysoni10** [comment]
@Deepu178 Thank you for assigning me this task. I will try to merge PR soon.

**Comment by Deepu178** [comment]
we are implementing different filter so closing the issue for now. thanks for creating the issue.
