### ISSUE TITLE
[BUG] Sign in with Google is not working.

### ISSUE THREAD

**Issue by Palaktahlyani** [UniKonf/Vibey#295]
### Description of the bug

Sign in with Google is not working.

### Please add screenshots (if applicable)

<img width="960" alt="Issue " src="https://github.com/UniKonf/vibey/assets/100354001/fd8e2da1-24a7-48b1-aff3-c05b3e7bcc1d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Palaktahlyani** [comment]
Can I work on this issue?

**Comment by Deepu178** [comment]
@Palaktahlyani Did  you follow the documentation properly to run the project locally?
