### ISSUE TITLE
[BUG] No event is happening after subscribing for a newsletter.

### ISSUE THREAD

**Issue by Palaktahlyani** [UniKonf/Vibey#296]
### Description of the bug

After entering the credentials in the newsletter's forms, no event is happening.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Palaktahlyani** [comment]
Can I work on it?

**Comment by Deepu178** [comment]
Thank you for taking the time to report the issue and bring it to our attention. We greatly appreciate your contribution to the project's development and your commitment to improving its overall quality. 

To help us address the issue effectively, we kindly request your assistance in providing any relevant details, steps to reproduce the problem, or additional information that can aid us in diagnosing and resolving the issue.

**Comment by Deepu178** [comment]
someone is working on the issue for now. thanks for creating the issue.
