### ISSUE TITLE
adding a preloader to the website

### ISSUE THREAD

**Issue by Illaf** [UniKonf/Vibey#300]
### Detailed description

Adding a react preloader in the website at the time of loading.

### Context

The website opens in a few milliseconds for which the user has to wait

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Illaf  Are you talking about adding preloader  through a package or making it by yourself using css? I need clarity it that coz we don't want to slow down the speed of the speed using too many packages.

**Comment by Illaf** [comment]
@Deepu178 I can make it both from package and pure html css as well. As for the package I will be using react loader because the website is made of react. react loader is a light dependency. 
However you can tell whichever way you want!

**Comment by Deepu178** [comment]
@Illaf  I would suggest to make the preloader using css but which kind of preloader you are gonna make? give me some idea about it

**Comment by Illaf** [comment]
@Deepu178 yeah sure I'll get you some designs
