### ISSUE TITLE
Adding hover affect in the explore events and subscribe buttons

### ISSUE THREAD

**Issue by Illaf** [UniKonf/Vibey#301]
### Detailed description

Adding rising and slight glow effects in the buttons when hovered

### Context

It will make the website look more dynamic and alive which attracts the user

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Illaf how are you gonna make? please provide me some reference so it will be easy to decide when we want this or not.

**Comment by Illaf** [comment]
@Deepu178 My idea is that on hovering over the button, it should get a bit raised with some box shadow and slight letter spacing
Also the 'vibey' logo can be given a less margin from the left and the github and get started icon should be more towards the right

**Comment by Deepu178** [comment]
someone is working on the issue for now. thanks for creating the issue.
