### ISSUE TITLE
Adding show password button

### ISSUE THREAD

**Issue by SubhamB2003** [UniKonf/Vibey#302]
### Detailed description

Hey, I want to add a show password button on the Sign-up and Sign-in page.

Can you please assign it to me under GSSOC'23?

### Context

![image](https://github.com/UniKonf/vibey/assets/94003231/913f8e7a-ec37-434c-9d2f-97eb576cd0be)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@SubhamB2003 There is already a pr for visibility of password in sign up but you can implement visibility of password in sign in.
Should I assign the issue for Sign in section?

**Comment by SubhamB2003** [comment]
> @SubhamB2003 There is already a pr for visibility of password in sign up but you can implement visibility of password in sign in. Should I assign the issue for Sign in section?

Yes, please

**Comment by Deepu178** [comment]
@SubhamB2003 I have assigned the issue!
looking forward to see your pr. 🚀🚀

**Comment by SubhamB2003** [comment]
> @SubhamB2003 I have assigned the issue! looking forward to see your pr. 🚀🚀

Hey, I created the PR can you please check
