### ISSUE TITLE
[FEATURE]: Add Captcha button in sign up form

### ISSUE THREAD

**Issue by Manice18** [UniKonf/Vibey#307]
### Detailed description

Will like to add captcha verification in the signup form before the create account is clicked.

### Context

A captcha keeps bot away from your website and differentiates it from human user.

### Possible implementation

I wont be using the google reCaptcha instead I would like to add captcha with my own logic ie with random alphanumeric characters.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Manice18 we are not looking for that right now.
