### ISSUE TITLE
 Update README.md

### ISSUE THREAD

**Issue by Swapnil-2503** [UniKonf/Vibey#309]
### Description of the bug

I want to work on updating readme.md according to codebase i will do it.

 Update README.md Description: Review and update the project's README.md file to provide comprehensive documentation and instructions for developers and contributors for making contribution to the project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Swapnil-2503 How would you improve existing Readme file? can you make some points?

**Comment by Deepu178** [comment]
@Swapnil-2503 How would you improve existing Readme file? can you make some points?

**Comment by Swapnil-2503** [comment]
@Deepu178 sorry ,  i didnt find any ideas other than folder structure that i can include, thank you.
