### ISSUE TITLE
[FEATURE] Add 'Powered by Vercel' logo on the footer

### ISSUE THREAD

**Issue by mkubdev** [UniKonf/Vibey#31]
### Detailed description

Hi, in order to list this repository as Vercel OSS Sponsor program, we need to brand the footer with this logo:
![logo](https://www.datocms-assets.com/31049/1618983297-powered-by-vercel.svg)

### Context

In order to match the requirements of Vercel's sponsorship program, we need to add this changes:

- A Vercel banner in the footer of each site page.
- A Vercel banner in the source repository's `README.md` file.
- All links back to Vercel should use a UTM tag with the format: `?utm_source=[team-name]&utm_campaign=oss`.

### Additional information

More Vercel design content to be found [here](https://vercel.com/design#dark-logotype).
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iambilalriaz** [comment]
Assign this task to me

**Comment by mkubdev** [comment]
Hi sure! :wave:

**Comment by iambilalriaz** [comment]
Hey @mkubdev - can you please send me `.env.local` variables so that I can get rid of this error:
`Please define the NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY environment variables inside .env.local`

**Comment by hariscs** [comment]
Hey @iambilalriaz, you can use the local data instead of the supabase,
Import it from lib > Data > events.ts

**Comment by mkubdev** [comment]
Hey @iambilalriaz ! Yes, sorry we need to update the readme accordingly to explain the steps to create a supabase session and get API keys. As @hariscs (thanks!) said, you can use local data to test.
Sorry again for the inconvenience.

**Comment by iambilalriaz** [comment]
Hey @mkubdev -  please review this PR https://github.com/WebXDAO/DevConf/pull/39

**Comment by mkubdev** [comment]
Fixed by #39
