### ISSUE TITLE
[FEATURE] Improving UI of the page

### ISSUE THREAD

**Issue by amittri1025** [UniKonf/Vibey#314]
### Detailed description

The buttons should have a Hover Effect, it will make website look more professional, kindly assign me this issue

![image](https://github.com/UniKonf/vibey/assets/74503582/f91d00a0-8e53-4e71-8981-a448c55e89cd)

### Context

Improving UI and overall experience of the webpage.

### Possible implementation

I will apply hover properties using Tailwindcss.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
not needed for now. thanks for creating the issue.
