### ISSUE TITLE
[FEATURE] No Hover on many things

### ISSUE THREAD

**Issue by amittri1025** [UniKonf/Vibey#316]
### Detailed description

Hover on boxes is not smooth, which does not gives good experience .

![image](https://github.com/UniKonf/vibey/assets/74503582/882e3cd4-bb96-474a-8c2e-ca709b5ef930)

![image](https://github.com/UniKonf/vibey/assets/74503582/dd12d8e1-95bf-4d3c-862e-13f5eb7146a1)

Kindly Assign me this , I will work on it.

### Context

User Experience improves

### Possible implementation

Using Tailwind CSS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Thankyou @amittri1025 for raising the issue. I'm assigning this issue to you. Are you contributing under GSSoC'23?

**Comment by money8203** [comment]
Closing this as not planned/relevant due to server migration
