### ISSUE TITLE
[IMPROVEMENT] Hidden Lines on the Terms and Conditions Page

### ISSUE THREAD

**Issue by Arcodex9** [UniKonf/Vibey#318]
**Description:**

The first two lines of the terms and conditions page are hidden under the header.
- Terms and Conditions
- Welcome to Vibey!

![1](https://github.com/UniKonf/vibey/assets/91794365/96943386-c77f-4ccb-b743-762806bd2d73)

Thanks

**Comment by tanishqamitra** [comment]
Hi! @Deepu178 I would like to work on this issue under GSSOC'23 and please assign the issue so I can start working on this issue.

**Comment by Deepu178** [comment]
Thanks @tanishqamitra for showing interest and I'm assigning the issue under GSSoC. Looking forward to review your pr 🚀🚀
