### ISSUE TITLE
Readme.md file enhancement

### ISSUE THREAD

**Issue by mahekkg** [UniKonf/Vibey#320]
### Detailed description

Hey, 
As a user, I believe that improving the visual presentation and accessibility of this section will greatly enhance the overall user experience and promote the effective communication of project values and principles. 
However, the current UI design for this section lacks visual appeal and fails to effectively highlight the essential information it contains.  
Please assign me this task. I have contributed to other projects successfully and can promptly work on this too.
Thank you

### Context

Different sections within a GitHub repository plays a crucial role in conveying the guiding principles, objectives, and philosophies of a project to potential contributors and users. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
already done
