### ISSUE TITLE
[FEATURE] Animated pointer

### ISSUE THREAD

**Issue by mahekkg** [UniKonf/Vibey#321]
### Detailed description

As an avid user and admirer of our already amazing website, I believe adding an animated pointer would greatly enhance the overall user experience and interaction. This animated pointer would serve as a visual guide, drawing attention to important elements, features, and actions on the website.

### Context

It is important to ensure that the animated pointer does not hinder accessibility or interfere with the usability of the website for users with disabilities or those who prefer alternative navigation methods.
The animated pointer should be subtle and not overshadow the content or distract users from their primary tasks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@mahekkg can you explain it in more detail like what exactly you are trying to do?

**Comment by mahekkg** [comment]
as the UI/UX looks great , this might add more to it.
I hope this picture explains it
![Screenshot (406)](https://github.com/UniKonf/vibey/assets/85817366/c2aa6e78-b5a2-412d-85ec-82b64add62e3)

**Comment by mahekkg** [comment]
@Deepu178 Hey can you update on the same?

**Comment by Deepu178** [comment]
@mahekkg I'm assigning this issue and are you contributing under gssoc?

**Comment by mahekkg** [comment]
@Deepu178 yes I am working under gssoc
Will promptly work on it

**Comment by Deepu178** [comment]
any update @mahekkg
