### ISSUE TITLE
Add documentation for installing the dependencies using pnpm package manager

### ISSUE THREAD

**Issue by Deepu178** [UniKonf/Vibey#324]
Adding pnpm to Vibey project provides efficient package management by using a single shared package store, reducing disk space usage, and accelerating installation and updates of dependencies.

**Comment by tanishqamitra** [comment]
Hi! @Deepu178
I would like to work on this issue under GSSOC'23 and please assign the issue so I can start working on this issue.

**Comment by Deepu178** [comment]
Thank you @tanishqamitra for showing interest and here I'm assigning this issue under GSSoC. Looking forward to review your pr.

**Comment by mandliyarajendra11** [comment]
i want to work on this issue
