### ISSUE TITLE
[FEATURE] Add Improved Hover Effect to cards

### ISSUE THREAD

**Issue by akash0708** [UniKonf/Vibey#325]
### Detailed description

The present hover effect is pretty abrupt, with the reddish tint appearing suddenly out of nowhere. I would like it to be a smooth transition, with the reddish tint appearing gradually from the bottom of each card on hovering over them.

### Context

It would improve the user experience by providing them a smooth transition.

### Possible implementation

![feature](https://github.com/UniKonf/vibey/assets/110753356/c93fb4f3-b621-4418-8ede-49b24772026c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Riyazul555** [comment]
Hey @akash0708 I know what to do here ....please assign me this issue under GSSOC 23
