### ISSUE TITLE
[FEATURE] Add Scroll to top button

### ISSUE THREAD

**Issue by komalioruganti** [UniKonf/Vibey#328]
### Detailed description

I want to add a button that scrolls to the top of the page from any position of the scroll bar to all the pages of the web app.

### Context

It gets quite frustrating if there are a number of Events or hackathons or CFPs in a page and the user wishes to go to scroll to the top. 

### Possible implementation

Adding a scroll to top button would solve this issue and increases user experience on this web app in such cases.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanbairagi30** [comment]
Hello , please assign me this issue , I am a good fit for this issue because I have once done the same type of functionality in my previous project , so I can do this type of stuff really easy.
Hoping to hear from you .

Thank you in advance .

**Comment by komalioruganti** [comment]
Can you assign me this issue?

**Comment by komalioruganti** [comment]
I have worked on multiple projects with a similar feature. I would love to contribute to your project by adding this feature. Can you assign me this issue?

**Comment by Deepu178** [comment]
already there
