### ISSUE TITLE
[FEATURE] Want to add Password Hide/Show button in login and signup page

### ISSUE THREAD

**Issue by HimanshuNarware** [UniKonf/Vibey#333]
### Detailed description

##Description
The login and Sign page does not have any button which use to show and hide passwords, I want to work on this feature please assign me this issue. This feature will improve the readability of the website.

### Context

This is important feature for the website, because this is related to the privacy of the user. and it also improve the readability of the website.

### Possible implementation

1.[ Added button to the login and signup page]
2.[Added login for button]

### Additional information

##Screenshot
![71](https://github.com/UniKonf/vibey/assets/83147410/8dc766e8-8d11-4a8c-9b49-c34973240a60)
![72-vibey](https://github.com/UniKonf/vibey/assets/83147410/4f6caf7f-c3b0-46b1-91e7-0b1226c64846)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
already pr for the issue
