### ISSUE TITLE
[FEATURE]: Impletement OAuth

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#339]
### Detailed description

Use OAuth as mentioned in the issue for the level3 template 

### Possible implementation

I would like to use the next auth for that, we can use built-in providers that are mentioned in the next auth or we can use custom providers, custom features.

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38 I am assigning the issue and please go ahead with Next auth. Looking forward for your pr
