### ISSUE TITLE
[FEATURE]: Validation in backend

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#340]
### Detailed description

Currently there is no validation in the backend, we can use a validator to validate the incoming data.,

### Context

The validators are needed so that we can prevent unwanted data formats or data formats that we should not inject into the database.

### Possible implementation

We can use an express validator for that.

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38 I have assigned the issue and  now you  can start working on the issue. I am looking forward for the changes that you have suggested.
