### ISSUE TITLE
[FEATURE]: Add Client side code for fetching events

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#342]
### Detailed description

I would like to add the client-side code for fetching events as mentioned in issue no 8

### Context

This is needed to populate the event page.

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Varghab** [comment]
@Deepu178 Hey, I want to work on this, please assign me the issue.
