### ISSUE TITLE
[FEATURE]: Add client side code for fetching CFPs in CFP Page

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#343]
### Detailed description

I would like to add the client-side code for fetching events as mentioned in issue no 9.

### Context

This is needed to populate the cfp page.

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
I have assigned the issue and you can start working on this issue. Good luck!
