### ISSUE TITLE
[FEATURE]: Add Custom form for adding events on client side in dashboard Description

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#345]
### Detailed description

I would like to add a custom form for adding events on the client side in the dashboard as mentioned in issue 6.

### Context

This is needed to get the events, CFPs and hackathons data and send it to the backend.

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38  This issue has already been assigned to someone else so you can look into other issues.
