### ISSUE TITLE
[FEATURE]: Event cards

### ISSUE THREAD

**Issue by anamika7153** [UniKonf/Vibey#346]
### Detailed description

- The image of the card and the content is getting mixed.
- The cards that have the image with contents on it are getting mixed with the contents on the card and making it a bit hard to read the content on the card properly.

### Context

I would like to add some stylings to the event cards to make the content visible clearly and look simple yet attractive.

<img width = "500" src="https://github.com/UniKonf/vibey/assets/66116440/db46ca33-41ec-45e5-b1ed-62292b4fbca3">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@anamika7153 so how are you gonna solve this issue? I mean how are you gonna implement the changes and can you explain a little bit?

**Comment by anamika7153** [comment]
> @anamika7153 so how are you gonna solve this issue? I mean how are you gonna implement the changes and can you explain a little bit?

@Deepu178  I will add a dark overlay between the background image and the content.

**Comment by Deepu178** [comment]
@anamika7153 I am assigning this issue and looking forward to see the changes that you have suggested. Are you contributing under GSSoC?

**Comment by anamika7153** [comment]
> @anamika7153 I am assigning this issue and looking forward to see the changes that you have suggested. Are you contributing under GSSoC?

Yes, I'm GSSoC'23 contributor
