### ISSUE TITLE
[docs]: Update README.md Description

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#347]
### Detailed description

Review and update the project's README.md file as mentioned in template issue no 1

### Context

this will help to better understandinga 

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38 Thanks for creating the issue.
I'm assigning this issue under GSSoC 🚀
Enjoy working on this issue.
