### ISSUE TITLE
[FEATURE]: Improve Dashboard for Contributors for adding events on client side Description

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#348]
### Detailed description

Improve Dashboard for Contributors for adding events on client side Description as mentioned in issue no 4

### Context

it will improve user experience

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38 Thanks for creating the issue.
I'm assigning this issue under GSSoC 🚀
Enjoy working on this issue.

**Comment by Deepu178** [comment]
@suzy-g38 any update on the issue?
