### ISSUE TITLE
The links of social media must open in a new tab

### ISSUE THREAD

**Issue by hardiksharma02** [UniKonf/Vibey#352]
### Description of the bug

the bug is that the social media links are being open in the same tab . So they must open in another tab . This will create a better user experience .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Thanks @hardiksharma02 for creating the issue.
Do you want to work on this issue?

**Comment by hardiksharma02** [comment]
@Deepu178 yes please assign me this task

**Comment by Deepu178** [comment]
I have assigned the task to you and you can start working on this project.
Are you contributing under GSSoC?

**Comment by hardiksharma02** [comment]
yes i am contributing under GSSoc
