### ISSUE TITLE
[FEATURE]Adding the Contact Us Page 

### ISSUE THREAD

**Issue by Vishalk91-4** [UniKonf/Vibey#356]
### Detailed description

I'll add the form, make it compatible with current UI and make it responsive 
Add some graphics to it
Add the email address, location and phone number to reach out

@Deepu178 , the link was there in the footer, but the page is not created, could you assign it to me so that a dedicated page can be added for it

### Context

When we click it on footer, we don't find it and it's necessary for contacting, reporting any issues 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Vishalk91-4  I have assigned the issue to  you and  you can start working on this issue. Good luck!

**Comment by Nishitbaria** [comment]
> @Vishalk91-4 I have assigned the issue to you and you can start working on this issue. Good luck!

Hey @Deepu178  I can Work On This issue if He is not working on this issue assign to me can i do in 1 day :)

**Comment by biplavmz** [comment]
Hii @Vishalk91-4 if you are not working it. I would like to work on it.

**Comment by money8203** [comment]
I think similar issue exists #269
