### ISSUE TITLE
[IMPROVEMENT] Improved newsletter section - design is given! 

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#359]
### Description of the bug

With due respect to the developer who created the newsletter section, I believe I can improve the current newsletter section. The problem with current newsletter section is -
- form field looks average. 
- the pink background used is unnecessary and makes the site more messy.
- simple section would look great and clean.

Please assign me this issue under GSSoC'23. 

I want to make something like this or more elegant than this  - 
![images (4)](https://github.com/UniKonf/vibey/assets/59419650/6e8bc21d-7f2f-4f87-8fe4-759661b4df87)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab Thanks for suggesting and coming forward to improve it. I'm assigning this issue to you and looking forward to see your changes. One more thing tell me if we can integrate any third for email newsletter.

**Comment by Varghab** [comment]
@Deepu178 We can use mailchimp or brevo to catch email subscribers and automate things accordingly from their platform.
