### ISSUE TITLE
[BUG] dark mode toggle is not visible

### ISSUE THREAD

**Issue by mandliyarajendra11** [UniKonf/Vibey#361]
### Description of the bug

When we click on "Get Started," the dark mode toggle does not appear due to its low z-index, and the **login/signup page is not designed** **in dark mode,** which is why it is being hidden. So, I will also make it dark mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@mandliyarajendra11 can you add a small video about what are you trying to fix here so it will give me more clarity about the issue.

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11 can you add a small video about what are you trying to fix here so it will give me more clarity about the issue.

![Screenshot (164)](https://github.com/UniKonf/vibey/assets/119125519/793da2e5-878a-438e-8f1e-04198af10fa6)

![Screenshot (163)](https://github.com/UniKonf/vibey/assets/119125519/79eb3cc1-7f8f-4a35-9a95-dcd686d7dc45)

**Comment by Deepu178** [comment]
@mandliyarajendra11 I have assigned this issue and are you contributing under GSSoC23?
Looking forward to see your pr and changes

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11 I have assigned this issue and are you contributing under GSSoC23? Looking forward to see your pr and changes

yes under gssoc

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11 I have assigned this issue and are you contributing under GSSoC23? Looking forward to see your pr and changes

i think it is level 2 issue because  fixing toggle z-index bug and   need to create sign up and login page dark mode page UI

**Comment by Deepu178** [comment]
@mandliyarajendra11 I'll suggest you to create pr if I think that issue has to be level2 then I'll change accordingly. It's not a problem and looking forward for your pr.

**Comment by mandliyarajendra11** [comment]
> @mandliyarajendra11 I'll suggest you to create pr if I think that issue has to be level2 then I'll change accordingly. It's not a problem and looking forward for your pr.

ok
