### ISSUE TITLE
[BUG] Navbar remains open on mobile

### ISSUE THREAD

**Issue by anamika7153** [UniKonf/Vibey#368]
### I'm in GSSoC'23

On mobile screens, navbar remains open after 
- clicking on any Navbar links

### Expected Behaviour
- Navbar should close instantly and the requested page should be displayed when the user clicks on any Navbar links.

### Please add screenshots (if applicable)

https://github.com/UniKonf/vibey/assets/66116440/0acd2542-cb0b-4f5a-bc91-5e8fe8656625

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@anamika7153 I'm assigning this issue under GSSoC23 and looking forward to see your changes in your pr.
