### ISSUE TITLE
[FEATURE] Add Authentication and Validation(User) Middlewares

### ISSUE THREAD

**Issue by Isha988** [UniKonf/Vibey#371]
### Detailed description

There is an absence of validation and authentication on the server side. For implementing them we can start with,
1. Authentication Middleware 
2. Validation middleware for user register and login routes.

### Context

This feature will prevent unauthenticated request and bad(user error) request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crocmons** [comment]
I want to also contribute on this issue

**Comment by Deepu178** [comment]
Thanks for creating the issue @Isha988 but this issue has already been assigned to @suzy-g38 so you can look into other issues or you can create new one.
