### ISSUE TITLE
Change the style of image from shrinkage to cover in Hero Section

### ISSUE THREAD

**Issue by rohankumarchaudhary67** [UniKonf/Vibey#375]
### Description of the bug

The current style of the image in the Hero Section is set to shrinkage, which is causing the image to be distorted and not displaying as intended. In order to improve the visual appearance and maintain the correct aspect ratio, we need to change the style of the image from shrinkage to cover.

Expected Behavior:
When the style of the image in the Hero Section is changed to cover, it should maintain its original aspect ratio and cover the entire available space within the designated area. This will ensure that the image is displayed correctly and enhances the overall aesthetic of the Hero Section.

### Please add screenshots (if applicable)

![Screenshot 2023-07-02 015410](https://github.com/UniKonf/vibey/assets/111426214/524a02f9-f2aa-4baf-91da-0f54924935c1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Thanks for creating the issue @rohankumarchaudhary67 and would you like to work on this issue?

**Comment by rohankumarchaudhary67** [comment]
Yeah Ofcourse, Please assign me
