### ISSUE TITLE
Adding a progress scrollbar at the top of the website

### ISSUE THREAD

**Issue by Illaf** [UniKonf/Vibey#379]
### Detailed description

A progress scrollbar which matches the theme of the website can be added to the top of the website. 

### Context

This will further enhance the features of the website and beautify it. It will add to the dynamic effects of the website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Illaf  How are you gonna implement this?

**Comment by Illaf** [comment]
@Deepu178 Please Have a look. you may see it at the top of the website

https://github.com/UniKonf/vibey/assets/114517448/08be9b1d-4e75-4c4c-83d8-fda23a64d69d

**Comment by Illaf** [comment]
@Deepu178 Please review this

**Comment by Deepu178** [comment]
@Illaf I'll review this pr soon as we are making significant changes so there may be issue while merging this pr. so kindly wait for sometime

**Comment by Illaf** [comment]
@Deepu178 Please if you approve this progress bar design then i can create a pr

**Comment by Deepu178** [comment]
@Illaf  assigned it. go ahead with the changes
