### ISSUE TITLE
[FEATURE] Show password button

### ISSUE THREAD

**Issue by shraddha761** [UniKonf/Vibey#383]
### Detailed description

Add show password button to sign up page as it is already present in sign in page

### Context

![image](https://github.com/UniKonf/vibey/assets/106100728/df49a2fa-dc04-41d1-ae92-a9bfcc0e4c23)

### Additional information

Assign this issue to me under GSSOs'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ranjanmangla1** [comment]
can any one assign me this issue?

**Comment by Deepu178** [comment]
Hey, there is a pr for this already so I'm closing it for now. @shraddha761 @ranjanmangla1 you can look into other issues or you can create new issues.
