### ISSUE TITLE
[BUG] About Us section UI

### ISSUE THREAD

**Issue by RitiChandak** [UniKonf/Vibey#386]
### Description of the bug

Fix the Messy About Us Page Card UI: Align Elements Properly and Enhance Visual Appeal
and multiple photos appearing in our team section need to be fixed

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/96969496/7ec6285a-fb00-43a1-a767-af3dd1fb8ab5)
![image](https://github.com/UniKonf/vibey/assets/96969496/2625899e-ec78-4aec-9fd9-8b3dea7600c5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@RitiChandak  This has already been assigned to @tanishqamitra so you can look into other issues or you can create new issues to work on .

**Comment by RitiChandak** [comment]
okay sir
