### ISSUE TITLE
[BUG] [UI] Social Icons in Footer are too Small! 

### ISSUE THREAD

**Issue by ranjanmangla1** [UniKonf/Vibey#388]
### Description of the bug

As we can see in the screenshot, social icons are very small, this lead to a bad user experience and this becomes worse in mobile screens, and from UI point of view, it is looking bad as well

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/93506927/1614a8d8-98ce-4809-acd6-4c955f5d3ddf)
![image](https://github.com/UniKonf/vibey/assets/93506927/79b15918-7ab2-43fd-9ab4-165afb8661af)

### Add any other context about the problem here

I would love to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vr1Ravi** [comment]
Hey it seems easy task for me that i can do. Allow me to work on this😊.

**Comment by mstfece** [comment]
I can handle it.
