### ISSUE TITLE
[FEATURE] Add scroll to top button

### ISSUE THREAD

**Issue by sumitkr2000** [UniKonf/Vibey#389]
### Detailed description

Hey, I want to add scroll to top button to the website. It will improve the user experience. Please assign me this issue. Thank you!

### Context

It will benefit the users if a user reach at the bottom of the website. They can simply go to the top using the scroll-to-top button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Thanks for creating the issue and I'm assigning it to you. Looking forward to review your pr.
