### ISSUE TITLE
[FEATURE] Show password button on the sign up page

### ISSUE THREAD

**Issue by sumitkr2000** [UniKonf/Vibey#390]
### Detailed description

Hey, I want to add the show password button on the signup page. Please assign me this issue. Thank you!

### Context

Users can see if the password they are typing is correct or not using the show password button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
This issue has already been assigned to another contributor and you can look into other issues.
