### ISSUE TITLE
[BUG] Fix Cards in About Page

### ISSUE THREAD

**Issue by Manice18** [UniKonf/Vibey#391]
### Description of the bug

The cards in the about page are off alignment and makes the UI look bad, hence I will like to fix this issue

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/91601706/2a2119e5-55ea-4515-ba54-64f774604e8d)
as you can see the cfp, events and conference are out of alignment.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
This issue has already been assigned to another contributor and you can look into other issues.
