### ISSUE TITLE
[FEATURE] Improve readme

### ISSUE THREAD

**Issue by Shikhar9425** [UniKonf/Vibey#395]
### Detailed description

update readme

### Context

want to add some more features to readme

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by Shikhar9425** [comment]
@Deepu178 please assign this issue to me

**Comment by Deepu178** [comment]
@Shikhar9425 How will you implement it? What kind of changes you are gonna make?

**Comment by Shikhar9425** [comment]
I want to add some features related to vibey in the readme and want to make the readme more impressive @Deepu178

**Comment by Shikhar9425** [comment]
> I want to add some features related to vibey in the readme and want to make the readme more impressive

@Deepu178

**Comment by Deepu178** [comment]
@Shikhar9425 already improved
