### ISSUE TITLE
[FEATURE] Hackathon Details Page

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#404]
### Detailed description

Hey, I want to create a Detailed page for the hackathon page. 

### Context

I have already created the events page, but the hackathon page will be different. Please assign me this issue under GSSoC'23 and with label. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab I have assigned the issue and looking forward to see the changes. good luck!
