### ISSUE TITLE
[BUG] getting server error

### ISSUE THREAD

**Issue by biplavmz** [UniKonf/Vibey#426]
### Description of the bug

while click on all events getting this error. using npm 

### Please add screenshots (if applicable)

<img width="712" alt="image" src="https://github.com/UniKonf/vibey/assets/68702055/157ddbec-1733-49dc-b4b5-8fac453edbd1">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
It has been resolved.
