### ISSUE TITLE
[BUG] ERR_TOO_MANY_REDIRECTS,  Vibey Site not working!

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#428]
### Description of the bug

Hey, I have just checked the site and it's not working. I have also checked my internet connection and it's working fine. The error says - ERR_TOO_MANY_REDIRECTS, Refer to the screenshot. 

### Please add screenshots (if applicable)

![Screenshot 2023-07-09 082123](https://github.com/UniKonf/vibey/assets/59419650/305954fa-8e87-4033-8de0-f214edc2b735)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab we have actually migrated the domain and have to update the name servers so yes it will take some time to update properly. It's  not any error I think it just takes some time.
