### ISSUE TITLE
[docs]: readme update for how to run project locally

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#431]
### Detailed description

I would like to add the documentation for how to run the client and the server locally

### Context

from the current readme how to run both client and server locally is not mentioned.

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38 I have assigned the issue and you can start working on this issue. Good luck!
