### ISSUE TITLE
[FEATURE] comments on PR yml

### ISSUE THREAD

**Issue by Abhinavcode13** [UniKonf/Vibey#434]
### Detailed description

Whenever a new PR is raised , it works automatically and makes the things simpler for the project admin and mentors.

If the changes in the PR specifically target the YAML file, use comments to draw attention to those modifications. Point out which lines or sections have been added, modified, or removed to make it easier for reviewers to identify and focus on the relevant changes.

 If a reviewer raises questions or requests clarification about certain aspects of the YAML file, respond to their comments directly in the YAML file. Provide clear explanations, examples, or references to relevant documentation to address their concerns.

### Context

f reviewers leave comments related to the YAML file, actively engage in the discussion. Respond to their comments, address any concerns, and collaborate to find the best solutions. Use the comment thread to foster productive communication and ensure that everyone involved understands the changes being made.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhinavcode13** [comment]
Please assign me this issue @Deepu178

**Comment by Deepu178** [comment]
@Abhinavcode13 I am assigning this issue under GSSoC and looking forward to see your pr. Good luck!
