### ISSUE TITLE
[BUG]  About page Know Everything About section ui improvement

### ISSUE THREAD

**Issue by SubhamB2003** [UniKonf/Vibey#438]
### Description of the bug

Hey, on the About page, the Know Everything About section UI is not good in both mobile and desktop views.
I want to change it. Can you please assign it to me?

![image](https://github.com/UniKonf/vibey/assets/94003231/04f2965c-0b62-4613-b2a6-f56232190f62)

Also, the image occurs in two time
![image](https://github.com/UniKonf/vibey/assets/94003231/fb46d387-5e3b-4fd1-a522-ba4697a68f54)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@SubhamB2003 This issue has been already resolved if you want to work on other issues I can help you to take on.

**Comment by SubhamB2003** [comment]
> 

Yeah ok,

Hey, on the sign-up page, there is no option to show the password it this issue is assigned.
if not then can I add it and I also open two issues can you assign them to me
