### ISSUE TITLE
[FEATURE]: Error handling for Client Side

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#440]
### Detailed description

Handle errors for user registration, login and all the pages where data is coming from API

### Context

As currently there is no specific error-handling part, I would work on it

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
I have assigned the issue and you can work on this issue. enjoy working on this issue.

**Comment by satya-nishanth** [comment]
@Deepu178 if @suzy-g38 is not working on it. Can you assign this to me?
