### ISSUE TITLE
Bug: change background color when auth model opens

### ISSUE THREAD

**Issue by tanishqamitra** [UniKonf/Vibey#460]
### Description of the bug

change background color when auth model opens 

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/105803534/44b1702c-a03f-489a-a13b-5b8d841532d2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@tanishqamitra would you like to work on this issue?

**Comment by tanishqamitra** [comment]
yes please assing me this issue under GSSoC'23
