### ISSUE TITLE
Adding svg of  instead of Button in sign in page 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [UniKonf/Vibey#462]
### Detailed description

![Screenshot from 2023-07-13 17-48-09](https://github.com/UniKonf/vibey/assets/98320971/dace8adc-70a0-43e1-b6f3-86b32b1aef86)

### Context

Wish to work under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@ShreyaDhiman24 This is a good suggestion and I'm assigning this issue under GSSoC.
