### ISSUE TITLE
Adding animation on of home page.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [UniKonf/Vibey#464]
### Context

Wish to work under GSSoC'23.

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@ShreyaDhiman24 can  you tell me what kind of animation you are talking about?

**Comment by ShreyaDhiman24** [comment]
@Deepu178 In this on hovering the resource gallery there is a slider effect or we can also add glowing effect accordingly which suits more good in this case. For example case I have provided you with the template below:
(We will change colour combos as per the website.)

[Screencast from 15-07-23 02:48:40 AM IST.webm](https://github.com/UniKonf/vibey/assets/98320971/f2f58cca-3662-4f21-9871-c9b5146d6d9d)

**Comment by Deepu178** [comment]
@ShreyaDhiman24 is this for Navbar or like where exactly do you want to add? I need more clarity on this.

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 is this for Navbar or like where exactly do you want to add? I need more clarity on this.
For highlighted part:

![image](https://github.com/UniKonf/vibey/assets/98320971/329b764a-942e-46f8-a145-e4edb65f1773)

**Comment by Deepu178** [comment]
okay @ShreyaDhiman24 assigning. ask for feedback when needed

**Comment by ShreyaDhiman24** [comment]
> okay @ShreyaDhiman24 assigning. ask for feedback when needed

okayy!
