### ISSUE TITLE
[FEATURE] Adding return to top scroll button.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [UniKonf/Vibey#468]
### Detailed description

![image](https://github.com/UniKonf/vibey/assets/98320971/5643bd8d-0da3-4f84-985b-f25222560508)

![image](https://github.com/UniKonf/vibey/assets/98320971/db27745d-e511-4ef8-9cbf-d7e4507dbce9)

### Context

Wish to work under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by money8203** [comment]
Hey @ShreyaDhiman24, thanks for opening the issue. I feel there's already a feature for what you're suggesting so closing the issue.
