### ISSUE TITLE
[DOCUMENTAION] Guide to set up the local server and connecting to the mongodb server

### ISSUE THREAD

**Issue by Varghab** [UniKonf/Vibey#469]
### Detailed description

There is no proper guide on setting up the server locally and connecting to the MongoDB server. Please assign me the issue, I will create proper documentation for this. 

### Context

**This is important or else contributors wouldn't be able to contribute on aspects requiring the site to be connected to the MongoDB server.** 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Varghab this is already in the documentation so I'm closing this for the time being if you think I'm missing something let me know.
