### ISSUE TITLE
Update Navbar Section

### ISSUE THREAD

**Issue by money8203** [UniKonf/Vibey#47]
### Detailed description

Include sections like Home, Conferences, Search, and CFP's 

### Context

It'll be helpful for people to navigate through he website and search for the thing they want

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saikat-Mandal** [comment]
@money8203 Can i work on it ?

**Comment by money8203** [comment]
@Saikat-Mandal You can work on other issues, this is currently in progress :)
