### ISSUE TITLE
[FEATURE] Add ARIA attributes to login and signup forms

### ISSUE THREAD

**Issue by Avinash905** [UniKonf/Vibey#476]
### Detailed description

Currently, our forms lack these attributes, hindering proper interpretation by assistive technologies.

### Context

ARIA attributes are crucial for enhancing web application accessibility, benefiting users with disabilities.

### Possible implementation

**Some steps to implement this enhancement-**

- Identify the login and signup form elements in your codebase.
- Determine the relevant ARIA attributes to add for each form element.
- Add ARIA roles to the forms and their elements (e.g., "form" role for the main form element).
- Include concise and descriptive ARIA labels using the aria-label attribute.
- Use the aria-describedby attribute to provide additional instructions for the forms.
- Implement ARIA states and properties (e.g., aria-required for required fields).
- Test the accessibility improvements using assistive technologies.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Deepu178** [comment]
@Avinash905 assigned the issue and looking forward to see the changes.
