### ISSUE TITLE
[FEATURE]: add github action to lock new issues

### ISSUE THREAD

**Issue by harmeetsingh11** [UniKonf/Vibey#494]
### Detailed description

The repository has 69 opened issues.
Issues receive more comments as a whole. As a result, the number of desktop and mobile notifications rises, making their management challenging for repository maintainers, admins. 

### Context

I will add the github action workflow, which will lock new new issues. This means that, when the new issue is created, it will be locked. The issue will be unlocked when the maintainer/admin will add `status: ready for dev` label to it. The admins and maintainers would greatly benefit from this, and it would also reduce notifications.

### Additional information

- [x] I'm a GSSoC'23 contributor.
- [x] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@harmeetsingh11 What can  you add more into it for making it better?

**Comment by harmeetsingh11** [comment]
Before locking the new issue, I can add Label to it like `gssoc23`. And github action will comment that "issue is locked, it will be unlocked once we add `status: ready for dev` label to it ".

**Comment by Deepu178** [comment]
okay, assigning it and need more contribution from you in gh actions.

**Comment by harmeetsingh11** [comment]
> okay, assigning it and need more contribution from you in gh actions.

Sure
