### ISSUE TITLE
[FEATURE] Want to improve the hover effect of the navbar content and social icons

### ISSUE THREAD

**Issue by HimanshuNarware** [UniKonf/Vibey#499]
### Detailed description

I Want to improve the hover effect of the navbar content and social icons,

### Context

This will improve the UI and the readability of the website.

### Possible implementation

-Add left to right animation on underline
-Add hover effect on the social icons

### Additional information

![78](https://github.com/UniKonf/vibey/assets/83147410/0b8702ca-ecf2-419f-936f-acb2c65b6b60)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suzy-g38** [comment]
@HimanshuNarware I am closing this issue as this is already done. Thanks for your contribution.
