### ISSUE TITLE
[BUG] Search Card Content

### ISSUE THREAD

**Issue by himanshu1221** [UniKonf/Vibey#50]
### Description of the bug

Whenever we click on the search bar the content it suggests is not fitting inside in the search bar card 

### Please add screenshots (if applicable)

![Screenshot from 2023-03-13 12-04-35](https://user-images.githubusercontent.com/32031706/224625535-02fe19c7-61b5-41aa-95d9-051665a99738.png)

### Add any other context about the problem here

I would love to work on this issue  if maintainer find this issue relevant 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Akhilbisht798** [comment]
I did'nt understand the problem you are referring to? Can you explain it with some more detail?

**Comment by himanshu1221** [comment]
> I did'nt understand the problem you are referring to? Can you explain it with some more detail?

In the latest version, I can see they have fixed this issue regarding search bar 

previously the suggested events were not in the frame and there was no scrollbar present to explore events
