### ISSUE TITLE
[FEATURE] Workflow to add labels to PR & issues by analyzing titles

### ISSUE THREAD

**Issue by Anmol-Baranwal** [UniKonf/Vibey#501]
### Detailed description

Suppose there is `fix` or `feat` or `chore` or `Feature` in the title, the workflow would automatically add the corresponding labels.

> I would do this under GSSoC'23.

### Context

I will separate this workflow into two files to improve code readability and labels will be in the trigger file.

By analyzing the titles of PRs, it will automatically assign appropriate labels based on predefined criteria such as status, goals, and aspects. It will use `regexs`, `events`, `targets`.

### Possible implementation

I will add detailed instructions in the PR description, so that you can easily review the PR.

I will add the labels, based on the repository and will mention if a new label is used for the purpose like `build`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anmol-Baranwal** [comment]
@Deepu178
Do you need this? Please close this, if this is irrelevant to the repository

**Comment by Deepu178** [comment]
@Anmol-Baranwal liked the idea. assigning you
