### ISSUE TITLE
[BUG] Refactor missing properties with interface in GetContributor.tsx 

### ISSUE THREAD

**Issue by Anmol-Baranwal** [UniKonf/Vibey#505]
### Description of the bug

- There is a missing `width` & `height` property with `Image` from next.js.

- Also, there is no interface involved in the page. What is even the advantage of TypeScript if we don't restrict type.

I will remove the errors, and add a proper Interface with the current rule set.

- Using `Link` rather than `a`. Reference docs: https://nextjs.org/learn/basics/navigate-between-pages/link-component

> I will do this under GSSoC'23.

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/74038190/71a72cbd-f7e4-4e60-90d8-90abcdd3d654)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Anmol-Baranwal assigned the issue and you can start working on the issue if you face any issue setting up the environment locally let me know. good luck!
