### ISSUE TITLE
[FEATURE]: Create forms for Cfp and Hackathon

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#511]
### Detailed description

I would like to create forms for hackathons and cfps

### Context

As the event is already done...so want to create the same for hackathons and cfps

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38 assigning the issue and looking forward to see your pr. good luck!

**Comment by Deepu178** [comment]
Any update @suzy-g38
