### ISSUE TITLE
Footer Icon Bug

### ISSUE THREAD

**Issue by Harshu467** [UniKonf/Vibey#513]
### Description of the bug

As of now in footer the icons of social media are too small , for professional website we must make it proper size

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/89975347/13791e48-fa68-4597-b865-3d1bc0bd1c56)

### Add any other context about the problem here

Assign it to me

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
already assigned to someone else
