### ISSUE TITLE
Button Bug

### ISSUE THREAD

**Issue by Harshu467** [UniKonf/Vibey#514]
### Description of the bug

As of now when clicked on buttons with empty fields , signup and login text are not visible

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/89975347/3f0c4d3b-86cf-466c-8c5f-90bc6891064c)
![image](https://github.com/UniKonf/vibey/assets/89975347/cf0cde38-70b3-4b5e-8cc3-fd4c3987741a)

### Add any other context about the problem here

Assign it to me

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Harshu467 someone is already working on this issue so closing for now
