### ISSUE TITLE
[style]: improve hover effect on profile card and profile picture

### ISSUE THREAD

**Issue by harmeetsingh11** [UniKonf/Vibey#524]
### Description:

On `Contributor` page, the hover effect on profile card and profile picture is not smooth, it instantly scales up which not looks good. I want to improve it by adding smooth transition and different hover effect on profile picture.

### Screenshots (Current styling) 
[Vibey.webm](https://github.com/UniKonf/vibey/assets/130365071/9266f5f4-5205-415c-927d-3983758f6978)

### Record
- [x] I agree to follow Contributing Guidelines and Code of conduct
- [x] I'm a GSSoC'23 Contributor
- [x] I want to work on this issue

**Comment by money8203** [comment]
@harmeetsingh11 do you have any specific style in mind or want to discuss about it ?

**Comment by harmeetsingh11** [comment]
Yes, I have the idea and demo video will be attached with the PR. 
I'll add transform property on profile card hover and animation on profile picture.

**Comment by money8203** [comment]
So, you've already started working on the issue ?

**Comment by harmeetsingh11** [comment]
Not exactly, I was waiting to be assigned.

**Comment by money8203** [comment]
great, you can start working on the issue and in the meanwhile join our [discord server](https://discord.gg/rutpp7Xr) and share your progress and ideas there

**Comment by money8203** [comment]
Also are you working on the issue under GSSoC ?

**Comment by harmeetsingh11** [comment]
Yes, I'm a GSSoC'23 contributor.
