### ISSUE TITLE
[BUG] Footer Icons

### ISSUE THREAD

**Issue by Harshu467** [UniKonf/Vibey#533]
### Description of the bug

As of now in footer , first section and second section has its elements in up down order, but icons are side by side. We can improve design and make it more standard by making it top down icons 

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/89975347/117dc2e6-7ea4-49c3-b7be-3fa162aae333)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Harshu467** [comment]
Assign it to me

**Comment by money8203** [comment]
Are you working it under GSSoC ?
