### ISSUE TITLE
[BUG] Privacy policy text

### ISSUE THREAD

**Issue by Vishalk91-4** [UniKonf/Vibey#536]
### Description of the bug

In the dark mode the text of privacy policy is not clearly visible

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/116670999/f9a4514e-f747-4479-bc7f-b12a03b0d43b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Vishalk91-4 there is not issue in the dark  mode. you should checkout from your side.
