### ISSUE TITLE
[BUG] Navbar does not close when clicking outside or scrolling

### ISSUE THREAD

**Issue by s2sharpit** [UniKonf/Vibey#537]
### Description of the bug

When the navbar dropdown is open and a user clicks outside of it or scrolls, the navbar dropdown should close automatically. Currently, this functionality is missing, causing inconvenience and inconsistent behavior for users.

### Please add screenshots (if applicable)

https://github.com/UniKonf/vibey/assets/104740281/a85d6d6d-d18f-4b80-b219-990dff19822a

### Add any other context about the problem here

Expected Behavior:
The navbar dropdown should close when the user clicks outside of it or scrolls the page.

Actual Behavior:
The navbar dropdown remains open even when the user clicks outside of it or scrolls the page.

Potential Solution:
One possible solution could be to add event listeners to detect clicks outside of the navbar dropdown or scroll events and trigger the closure of the dropdown when these events occur.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@s2sharpit  Varghab is working on new navbar so he will resolve the issue. I'm closing this issue for now.
