### ISSUE TITLE
[FEATURE]: Update Validation for Events

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#541]
### Detailed description

We need to change the event schema validation for events.

### Context

As the database structure for events has changed we need to update the backend validation according to the event schema as well.

### Additional information

 I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38  assigned the issue and looking forward to see pr.
