### ISSUE TITLE
[FEATURE]: Update validation for hackathon

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#542]
### Detailed description

I would like to update the hackathon validation schema.

### Context

As the database structure for hackathon has changed we need to update the backend validation for hackathon according to the hackathon validation schema.

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@suzy-g38 assigned the issue. good luck!
