### ISSUE TITLE
[FEATURE]: Update validation for Cfp

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#543]
### Detailed description

We need to change the cfp schema validation for cfps.

### Context

As the database schema for cfp has changed we need to update the backend validation according to the mongo cfp schema as well.

### Additional information

I would like to work on it under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
assigned it @suzy-g38
