### ISSUE TITLE
Confirmed Login Without Login

### ISSUE THREAD

**Issue by Souravvmishra** [UniKonf/Vibey#552]
### Description of the bug

When Clicked in the login with google button, ut confirmed the login using the toaster without logging in.

Same thing happened for login with GitHub.

### Please add screenshots (if applicable)

![Screenshot_2023-07-30-11-26-02-658_com android chrome](https://github.com/UniKonf/vibey/assets/89072785/dc28d4a1-7eb4-4d27-a3f9-7e417ebeb5d2)

![Uploading Screenshot_2023-07-30-11-26-02-658_com.android.chrome.jpg…]()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Souravvmishra how will you fix the issue?

**Comment by Souravvmishra** [comment]
By Showing The Toast Only After The Sign In process has completed

**Comment by Deepu178** [comment]
@Souravvmishra 
assigning the issue and make more good ui for the toast.  Are you contributing under GSSoC?

**Comment by Souravvmishra** [comment]
Yes

**Comment by Souravvmishra** [comment]
@Deepu178 Sir Any Update?
