### ISSUE TITLE
[FEATURE]: Dashboard for Contributors to add Cfps from the client side

### ISSUE THREAD

**Issue by suzy-g38** [UniKonf/Vibey#557]
### Detailed description

Add a separate section for adding, and edit cfps on the client side

### Context

It will help the contributors to add and edit cfp data

### Additional information

I would like to work on this under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
assigned it @suzy-g38
