### ISSUE TITLE
[style]: add animation when subscription is successful

### ISSUE THREAD

**Issue by harmeetsingh11** [UniKonf/Vibey#559]
## Description:
In newsletter subscription section, when subscribe button is clicked, nothing happens and the email object is logged on browser console which is generally should not happen in production code.

I will add animation effect when subscription is successful and also remove the logged object from browser's console.

## Screenshot
![vibey](https://github.com/UniKonf/vibey/assets/130365071/5686ca11-279c-4263-b13a-32d165cf5117)

## Record
- [x] I agree to follow this project's Code of Conduct 
- [x] I'm a GSSoC'23 contributor
- [x] I want to work on this issue

Please assign me this issue under GSSoC'23
Thanks

**Comment by Deepu178** [comment]
@harmeetsingh11 assigning the issue for adding animation to the email subscription part. good luck with the issue
