### ISSUE TITLE
[BUG]  Newsletter Subscription Functionality Not Working and Email Notification Enhancement

### ISSUE THREAD

**Issue by Nishitbaria** [UniKonf/Vibey#560]
### Description of the bug

Currently, the newsletter subscription functionality in our application is not working as expected, and new subscribers are not being added to the system. Additionally, there is a missing feature where the owner of the application should receive an email notification whenever a new subscriber submits their information. This issue aims to address both problems, fixing the newsletter subscription functionality and adding the automatic email notification feature.

1. **Newsletter Subscription Issue:** When users attempt to subscribe to the newsletter, their information is not being successfully recorded in the database. The system should be designed to store the subscriber's email address along with any other relevant details, allowing us to keep our subscribers updated with the latest information.

2. **Email Notification Enhancement:** Currently, the application lacks a mechanism to notify the owner (admin) whenever a new user subscribes to the newsletter. This feature is essential to enable the owner to keep track of new subscribers and engage with them effectively.

### Expected Changes
To resolve the issues mentioned above, the following changes need to be implemented:

1. **Fixing Newsletter Subscription Functionality:**
   - Investigate the existing code to identify the root cause of the problem.
   - Rectify any bugs or errors that are preventing new subscribers from being added to the database.
   - Implement proper validation to ensure only valid email addresses are accepted for subscription.
   - Test thoroughly to verify that the newsletter subscription functionality is now working correctly.

2. **Adding Automatic Email Notification:**
   - Integrate an email notification service (e.g., SMTP or a third-party service) with the application.
   - Create a new email template/notification to be sent to the owner/admin upon a new subscriber submission.
   - Configure the application to send an automatic email notification to the owner/admin whenever a new subscriber successfully submits their information.
   - Ensure the email includes relevant subscriber details to facilitate efficient communication.

### Please add screenshots (if applicable)

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/85815172/371f6780-189a-411f-bca7-b8950ad59080)
![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/85815172/dc55efe5-8890-42c8-b901-effc007f2806)

![image](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/85815172/f6e93be4-2cd9-44c7-a6df-b47f5a175b62)

### Add any other context about the problem here

@Deepu178 ,please assign me this issue ,i will create pull request asap

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@Nishitbaria assigning the issue and looking forward to see the changes from your side.
