### ISSUE TITLE
[BUG] Privacy Policy Page Text Contrast Issue in Light Theme

### ISSUE THREAD

**Issue by s2sharpit** [UniKonf/Vibey#569]
## Issue:
The privacy policy page text exhibits contrast issues in the light theme, making it difficult to read.

## Suggested Solution:
I propose fixing the text contrast on the privacy policy page to improve readability in the light theme.

Please feel free to provide any additional information or suggestions.

Link: https://www.vibey.live/privacy

### Please add screenshots (if applicable)

https://github.com/UniKonf/vibey/assets/104740281/2a2159cf-19db-466f-94ea-d3de28401c76

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@s2sharpit assigned the issue and good luck!
