### ISSUE TITLE
[FEATURE] Aligning social icons horizontally for mobile screens.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [UniKonf/Vibey#575]
### Detailed description

![Screenshot from 2023-08-04 20-36-52](https://github.com/UniKonf/vibey/assets/98320971/a01c0446-f77c-43ca-b4f6-68d38c0d33da)

### Context

Want to work under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
assigned the issue @ShreyaDhiman24
