### ISSUE TITLE
[FEATURE] Simplify Theme Implementation with next-themes

### ISSUE THREAD

**Issue by s2sharpit** [UniKonf/Vibey#576]
## Issue Description:
Currently, our project requires us to call context and use useContext in every component to handle theming. This approach can be cumbersome and repetitive. To improve the implementation and ensure consistency across components, I propose migrating to the `next-themes` library.

## Suggested Solution:
The `next-themes` library provides a straightforward and elegant solution for managing themes in Next.js projects. By adopting `next-themes`, we can simplify the process of theming our components, reducing boilerplate code, and enhancing overall code readability.

## Benefits of Migrating to next-themes:
1. **Ease of Use**: `next-themes` abstracts the complexity of theme handling, allowing us to easily toggle between light and dark themes without manually managing context in every component.
2. **Consistency**: With `next-themes`, the theming implementation will be consistent across the application, leading to a more maintainable and predictable codebase.
3. **Performance**: The `next-themes` library is built with performance in mind, ensuring minimal impact on page load times and user experience.
4. **Future-Proof**: `next-themes` is actively maintained and updated, reducing the risk of deprecated code and ensuring compatibility with future Next.js releases.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
@s2sharpit assigned the issue and good luck!
