### ISSUE TITLE
[BUG] Remove duplicate Event

### ISSUE THREAD

**Issue by Prajwal0225** [UniKonf/Vibey#593]
### Description of the bug

There are two cards related to web3Conf India in Events section:

### Please add screenshots (if applicable)

![image](https://github.com/UniKonf/vibey/assets/103810119/290c8555-73ba-4809-8d61-3e810ac5df69)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suzy-g38** [comment]
Hey @Prajwal0225 this happened because of the dummy data from the database. It will be removed eventually. You can create other issues. Thank you.
