### ISSUE TITLE
add CFPs and Hackathons pages to show the CFPs and Hackathons happening

### ISSUE THREAD

**Issue by shafahad09** [UniKonf/Vibey#65]
### Detailed description
 - When navigating to the events, CFPs or hackathons page from navbar it shows error 404 (This page could not be found).
 
### Possible solution
- updating the links

### Please add screenshots (if applicable)

![Screenshot from 2023-04-07 23-07-16](https://user-images.githubusercontent.com/79015338/230654220-6abe4b1b-08ed-4aad-b076-c6dfcfbcea4e.png)
![Screenshot from 2023-04-07 23-07-25](https://user-images.githubusercontent.com/79015338/230654232-0e1e0bb8-1293-40cb-b259-3ed8b4fe8f85.png)
![Screenshot from 2023-04-07 23-07-34](https://user-images.githubusercontent.com/79015338/230654237-1c5cc197-af7c-4b6b-8573-7a54a24c2471.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Yes, we are working on thses pages and if you want to work on CFPs and Hackathons. @shafahad09

**Comment by shafahad09** [comment]
I really wish I could work on those two pages, but I am at the beginner level in JavaScript. I might be able to do this by taking some time and figuring it out myself, but I don't want to make fake promises. So, assign this to other people. When I am capable of doing things at that level I'll surely work on Vibey.

**Comment by Mudassirkhan2** [comment]
> Yes, we are working on thses pages and if you want to work on CFPs and Hackathons. @shafahad09 

I want to contribute in this from where can I get more details.

**Comment by Deepu178** [comment]
Hii, @Mudassirkhan2 Join the discord server for detailed discussion. 
https://discord.gg/KRSRMWhQ

**Comment by sid-talesara** [comment]
@Deepu178  I guess, discord link is not working

**Comment by mkubdev** [comment]
> @Deepu178 I guess, discord link is not working

Hi, please try this link: https://discord.gg/qT7xRPzB

**Comment by Deepu178** [comment]
@mkubdev  any update?

**Comment by Himan-Miku** [comment]
Hey, can I work on this issue?

**Comment by Raksha-Motiramani** [comment]
can i contribute to this

**Comment by sanyamx** [comment]
what are the updates on the issue?

**Comment by Deepu178** [comment]
> Hey, can I work on this issue?

Do you want to work on this issue?

**Comment by money8203** [comment]
@Mudassirkhan2 you want to take on this issue I think it's been in stale mode for quite a time?

**Comment by Mudassirkhan2** [comment]
Is their any figma File ? @money8203

**Comment by money8203** [comment]
Currently no, you need to make your own figma design and suggest it to us!

**Comment by Deepu178** [comment]
This issue has been resolved and don't need any work right now. So I am closing this issue for now.
