### ISSUE TITLE
suggest: migrate to `pnpm`

### ISSUE THREAD

**Issue by priyankarpal** [UniKonf/Vibey#66]
### Detailed description

We are using `npm` in this project. But we can use `pnpm` instead of `npm`. 

### Context

`pnpm` is that it provides a faster and more efficient installation process. This is because `pnpm` is able to leverage the shared global store to avoid installing duplicate dependencies across multiple projects. 

### Possible implementation

we can use `pnpm` instead of `npm`.

### Additional information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Actually, we are migrating to yarn.

**Comment by priyankarpal** [comment]
> Actually, we are migrating to yarn.

okk
