### ISSUE TITLE
ci: add dependabot

### ISSUE THREAD

**Issue by priyankarpal** [UniKonf/Vibey#67]
### Detailed description

We can add dependabot to upgrade all gh actions to the latest version if there are any updates needed.

### Context

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Can you explain it in more details?
How will it work or is there any breakable changes due to upgrading dependencies?

**Comment by priyankarpal** [comment]
> Can you explain it in more details? How will it work or is there any breakable changes due to upgrading dependencies?

Dependabot will upgrade all gh actions if there are any updates needed. Don't worry dependabot will create a PR to change.

**Comment by Deepu178** [comment]
That's good, would you love to work on this issue?

**Comment by priyankarpal** [comment]
> That's good, would you love to work on this issue?

yeah I want to work on this issue.
