### ISSUE TITLE
[BUG] Spelling mistake of hackathons

### ISSUE THREAD

**Issue by shafahad09** [UniKonf/Vibey#68]
### Description of the bug

- Hackathons is spelled incorrectly (Hackthons) in the navigation bar.

### Please add screenshots (if applicable)

![Screenshot from 2023-04-07 23-27-31](https://user-images.githubusercontent.com/79015338/230655336-5c6e66bf-e793-4a0d-a955-fcf5f7480664.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by money8203** [comment]
Wanna take this @shafahad09 ?

**Comment by shafahad09** [comment]
Sure. Thanks for assigning.

**Comment by shafahad09** [comment]
Hey @money8203 ,
Since I am just fixing a bug and not adding a new feature, do you want me to make changes directly to the main branch or do you want me to create a new branch?

**Comment by money8203** [comment]
Create a new branch and then proceed

**Comment by shafahad09** [comment]
Thanks 👍

**Comment by shafahad09** [comment]
Solved the issue and created a pull request.
