### ISSUE TITLE
[BUG] Error in "How to contribute" section of documentation 

### ISSUE THREAD

**Issue by shafahad09** [UniKonf/Vibey#71]
### Description of the bug

- In the "How to contribute" section of documentation, after the 4th step (making changes) the 5th step directly advices to commit the changes without staging.
- For this to work we need to use the command `git commit -a -m "Add some feature"`
- But the documentation shows `git commit -m "Add some feature"` which doesn't work unless we had already staged the files using `git add .`

### Possible solution:
- Update the `git commit -m "Add some feature"` to `git commit -a -m "Add some feature"`

### Please add screenshots (if applicable)

![doc](https://user-images.githubusercontent.com/79015338/230706067-9859a734-08b9-4a68-b0ae-685b832a23ea.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shafahad09** [comment]
Assign this to me.

**Comment by Deepu178** [comment]
you can work on the documentation @shafahad09
