### ISSUE TITLE
KubeCon CloudNativeCon Europe 2023

### ISSUE THREAD

**Issue by justankiit** [UniKonf/Vibey#75]
### Event Name

KubeCon + CloudNativeCon Europe 2023

### Short Description of the Event ( 20 words )

KubeCon is a great place to learn about current trends and new technologies in the Kubernetes ecosystem. At KubeCon you are able to get access to topics that you’d be hard pressed to find anywhere else. 
CNCF’s flagship conference gathers adopters & technologists from leading OS and cloud native communities (Kubernetes, Prometheus, Envoy, CoreDNS and more) for education and advancement of cloud native computing.
The Cloud Native Computing Foundation’s flagship conference gathers adopters and technologists from leading open source and cloud native communities in Amsterdam, The Netherlands from 18-21 April, 2023. Join our CNCF Graduated and Incubating Projects as the community gathers for five days to further the education and advancement of cloud native computing.

### Event Date and Time

18/04/2023-21/04/2023

### Event Page Link

https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/

### Themes

DEVOPS,OPEN-SOURCE,DEVREL,KUBERNETES

### LinkedIn

https://www.linkedin.com/company/cloud-native-computing-foundation/

### Twitter

https://twitter.com/CloudNativeFdn

**Comment by Deepu178** [comment]
We have added KubeCon CloudNativeCon Europe 2023.
Thanks @kumarankit999
