### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by justankiit** [UniKonf/Vibey#82]
### Description of the bug

At the bottom of page , the "Powered by Vercel " where is being written. In white mode it is in white colour and in dark mode it is also in white mode, In white mode the font is also in white color, Which not looks good, or by any mistake it is not taken up in  white mode.

### Please add screenshots (if applicable)

![vibey](https://user-images.githubusercontent.com/111564362/232974757-6ed94559-4ea1-4ed6-8e6e-d8567db170f2.jpg)

### Add any other context about the problem here

Change the white to black color font in the file ,make the fill in black

![vibey1](https://user-images.githubusercontent.com/111564362/232975800-a1342a7e-8897-418c-81b1-aa54aa3d75f2.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
do you want to work on this issue?

**Comment by justankiit** [comment]
No, Not now
