### ISSUE TITLE
[BUG] Not found the supporting link

### ISSUE THREAD

**Issue by justankiit** [UniKonf/Vibey#85]
### Description of the bug

In the Events Section, the Upcoming events Card not have a directed link in it, By which people get to know about the event Information .

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/111564362/233799803-c33942d9-fac4-45f1-9d13-5101f059e0bc.png)

### Add any other context about the problem here

We can add the directed link in the HTML tag </>,So that it can be Accessible for all other people Who want to get the information, or we can Create a button below the info. that by Read More which will be written in the button.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deepu178** [comment]
Actually this is just demo data and we are setting up the database. Once it is done we'll be redirecting to the events page.

**Comment by justankiit** [comment]
That's Great , We can work on this issue

**Comment by Deepu178** [comment]
sure, @kumarankit999
