### ISSUE TITLE
[BUG] Unhandled Runtime Error

### ISSUE THREAD

**Issue by priyankarpal** [UniKonf/Vibey#90]
### Description of the bug

When we try to run the project we are facing the server-rendered errors.

There are three errors. 
I already added `.env` file to the root & also added the tokens

How to check the error?

run the project by `yarn run dev`
& check the console or browser.the 

### Please add screenshots (if applicable)

![Screenshot from 2023-04-24 19-56-25](https://user-images.githubusercontent.com/88102392/234028515-75d2bc02-6be1-43b1-af7d-bccb235f7f86.png)
![Screenshot from 2023-04-24 19-56-28](https://user-images.githubusercontent.com/88102392/234028535-7b8d519f-f4c5-4f47-a18f-af76e885ebe0.png)
![Screenshot from 2023-04-24 19-56-31](https://user-images.githubusercontent.com/88102392/234028539-03a43dd5-7e60-4f54-9384-d7d8e6cb7853.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arunavabasucom** [comment]
I would like to work on this!

**Comment by Deepu178** [comment]
This issue has been fixed by @suzy-g38 and no longer needed help.
