### ISSUE TITLE
[BUG] sign up problem

### ISSUE THREAD

**Issue by priyankarpal** [UniKonf/Vibey#91]
### Description of the bug

1. When we successfully sign up the dashboard is showing but not showing the user's pfp. Showing another one's pfp. Also, still there `get started` button. I think we need to change the button to `dashboard` after successful login/sign up

2. After creating an account when we go to the `homepage` we need to create an account again.

Check the screenshot & screen recording

### Please add screenshots (if applicable)

![Group 1](https://user-images.githubusercontent.com/88102392/234036984-3d22ef4d-1609-4c8c-8d18-12afc9a6d5e7.png)

https://user-images.githubusercontent.com/88102392/234037334-30609539-9e12-4d23-8847-d35c0dcf3289.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hi @priyankarpal 👋🏻 ,

1. The picture is Chandra after redirection because the image is hardcoded here:
https://github.com/UniKonf/vibey/blob/b0f3d20b839b18fd3855eb95cbb071a43468698a/src/pages/dashboard/index.tsx#L263

We should replace this with the image from the Appwrite OAuth session once connected.

2. Look like the Auth workflow is not completed yet!

**Comment by priyankarpal** [comment]
> Hi @priyankarpal 👋🏻 ,
> 
> 1. The picture is Chandra after redirection because the image is hardcoded here:
>    https://github.com/UniKonf/vibey/blob/b0f3d20b839b18fd3855eb95cbb071a43468698a/src/pages/dashboard/index.tsx#L263
> 
> We should replace this with the image from the Appwrite OAuth session once connected.
> 
> 2. Look like the Auth workflow is not completed yet!

ok ok

**Comment by djv03** [comment]
is this issue still closed? otherwise I am taking over it

**Comment by Deepu178** [comment]
@djv03 do you want to work on this issue?

**Comment by djv03** [comment]
I working on it

**Comment by Deepanshu0703** [comment]
I can work on it if this issue is still not resolved  so can you assign it to me @money8203

**Comment by money8203** [comment]
@Deepu178 do we still needs changes for this issue?

**Comment by Deepu178** [comment]
Actually It's needed but as we recently decided to shift on proper backend so it may not be useful.
